### ISSUE TITLE
bundle exec rake ts:index

### ISSUE THREAD

**Issue by 419371274** [sharetribe/sharetribe#1390] opened 2015-08-14 14:39 UTC
bundle exec rake ts:index --trace
/usr/local/lib/ruby/gems/2.1.0/gems/bundler-1.10.6/lib/bundler.rb:315: warning: Insecure world writable dir /usr/local/lib/ruby/gems/2.1.0 in PATH, mode 040777
** Invoke ts:index (first_time)
** Invoke environment (first_time)
** Execute environment
INFO Connecting to database specified by database.yml

AssetSync enabled: false

Using the following AssetSync configuration:
aws_access_key_id:     Not available
aws_secret_access_key: Not available
fog_directory:         Not available
fog_provider:          Not available

AssetSync enabled: false

Using the following AssetSync configuration:
aws_access_key_id:     Not available
aws_secret_access_key: Not available
fog_directory:         Not available
fog_provider:          Not available

** Execute ts:index
Generating configuration to /home/ubuntu/sharetribe/mirror/config/development.sphinx.conf
WARN Creating scope :public. Overwriting existing method Listing.public.
WARN Creating scope :private. Overwriting existing method Listing.private.
rake aborted!
NoMethodError: undefined method `[]=' for nil:NilClass
/usr/local/lib/ruby/gems/2.1.0/gems/delayed_paperclip-2.9.1/lib/delayed_paperclip.rb:52:in `process_in_background'
/home/ubuntu/sharetribe/mirror/app/models/community.rb:205:in `<class:Community>'
/home/ubuntu/sharetribe/mirror/app/models/community.rb:105:in `<top (required)>'
/usr/local/lib/ruby/gems/2.1.0/gems/zeus-0.15.1/lib/zeus/load_tracking.rb:50:in `load'
/usr/local/lib/ruby/gems/2.1.0/gems/zeus-0.15.1/lib/zeus/load_tracking.rb:50:in `load'
/usr/local/lib/ruby/gems/2.1.0/gems/activesupport-3.2.21/lib/active_support/dependencies.rb:469:in `block in load_file'
/usr/local/lib/ruby/gems/2.1.0/gems/activesupport-3.2.21/lib/active_support/dependencies.rb:639:in `new_constants_in'
/usr/local/lib/ruby/gems/2.1.0/gems/activesupport-3.2.21/lib/active_support/dependencies.rb:468:in `load_file'
/usr/local/lib/ruby/gems/2.1.0/gems/activesupport-3.2.21/lib/active_support/dependencies.rb:353:in `require_or_load'
/usr/local/lib/ruby/gems/2.1.0/gems/activesupport-3.2.21/lib/active_support/dependencies.rb:502:in `load_missing_constant'
/usr/local/lib/ruby/gems/2.1.0/gems/activesupport-3.2.21/lib/active_support/dependencies.rb:192:in `block in const_missing'
/usr/local/lib/ruby/gems/2.1.0/gems/activesupport-3.2.21/lib/active_support/dependencies.rb:190:in `each'
/usr/local/lib/ruby/gems/2.1.0/gems/activesupport-3.2.21/lib/active_support/dependencies.rb:190:in `const_missing'
/usr/local/lib/ruby/gems/2.1.0/gems/activesupport-3.2.21/lib/active_support/dependencies.rb:514:in `load_missing_constant'
/usr/local/lib/ruby/gems/2.1.0/gems/activesupport-3.2.21/lib/active_support/dependencies.rb:192:in `block in const_missing'
/usr/local/lib/ruby/gems/2.1.0/gems/activesupport-3.2.21/lib/active_support/dependencies.rb:190:in `each'
/usr/local/lib/ruby/gems/2.1.0/gems/activesupport-3.2.21/lib/active_support/dependencies.rb:190:in `const_missing'
/usr/local/lib/ruby/gems/2.1.0/gems/activesupport-3.2.21/lib/active_support/inflector/methods.rb:230:in `block in constantize'
/usr/local/lib/ruby/gems/2.1.0/gems/activesupport-3.2.21/lib/active_support/inflector/methods.rb:229:in `each'
/usr/local/lib/ruby/gems/2.1.0/gems/activesupport-3.2.21/lib/active_support/inflector/methods.rb:229:in `constantize'
/usr/local/lib/ruby/gems/2.1.0/gems/activesupport-3.2.21/lib/active_support/dependencies.rb:554:in `get'
/usr/local/lib/ruby/gems/2.1.0/gems/activesupport-3.2.21/lib/active_support/dependencies.rb:588:in `constantize'
/usr/local/lib/ruby/gems/2.1.0/gems/activerecord-3.2.21/lib/active_record/inheritance.rb:103:in `block in compute_type'
/usr/local/lib/ruby/gems/2.1.0/gems/activerecord-3.2.21/lib/active_record/inheritance.rb:101:in `each'
/usr/local/lib/ruby/gems/2.1.0/gems/activerecord-3.2.21/lib/active_record/inheritance.rb:101:in `compute_type'
/usr/local/lib/ruby/gems/2.1.0/gems/activerecord-3.2.21/lib/active_record/reflection.rb:172:in `klass'
/usr/local/lib/ruby/gems/2.1.0/gems/thinking-sphinx-3.1.4/lib/thinking_sphinx/active_record/attribute/type.rb:37:in `block in associations'
/usr/local/lib/ruby/gems/2.1.0/gems/thinking-sphinx-3.1.4/lib/thinking_sphinx/active_record/attribute/type.rb:35:in `collect'
/usr/local/lib/ruby/gems/2.1.0/gems/thinking-sphinx-3.1.4/lib/thinking_sphinx/active_record/attribute/type.rb:35:in `associations'
/usr/local/lib/ruby/gems/2.1.0/gems/thinking-sphinx-3.1.4/lib/thinking_sphinx/active_record/attribute/type.rb:62:in `multi_from_associations'
/usr/local/lib/ruby/gems/2.1.0/gems/thinking-sphinx-3.1.4/lib/thinking_sphinx/active_record/attribute/type.rb:9:in `multi?'
/usr/local/lib/ruby/gems/2.1.0/gems/thinking-sphinx-3.1.4/lib/thinking_sphinx/active_record/attribute.rb:4:in `multi?'
/usr/local/lib/ruby/gems/2.1.0/gems/thinking-sphinx-3.1.4/lib/thinking_sphinx/active_record/attribute/sphinx_presenter.rb:19:in `collection_type'
/usr/local/lib/ruby/gems/2.1.0/gems/thinking-sphinx-3.1.4/lib/thinking_sphinx/active_record/sql_source.rb:96:in `block in append_presenter_to_attribute_array'
/usr/local/lib/ruby/gems/2.1.0/gems/thinking-sphinx-3.1.4/lib/thinking_sphinx/active_record/sql_source.rb:93:in `each'
/usr/local/lib/ruby/gems/2.1.0/gems/thinking-sphinx-3.1.4/lib/thinking_sphinx/active_record/sql_source.rb:93:in `append_presenter_to_attribute_array'
/usr/local/lib/ruby/gems/2.1.0/gems/thinking-sphinx-3.1.4/lib/thinking_sphinx/active_record/sql_source.rb:131:in `prepare_for_render'
/usr/local/lib/ruby/gems/2.1.0/gems/thinking-sphinx-3.1.4/lib/thinking_sphinx/active_record/sql_source.rb:65:in `render'
/usr/local/lib/ruby/gems/2.1.0/gems/riddle-1.5.12/lib/riddle/configuration/index.rb:29:in `block in render'
/usr/local/lib/ruby/gems/2.1.0/gems/riddle-1.5.12/lib/riddle/configuration/index.rb:29:in `collect'
/usr/local/lib/ruby/gems/2.1.0/gems/riddle-1.5.12/lib/riddle/configuration/index.rb:29:in `render'
/usr/local/lib/ruby/gems/2.1.0/gems/thinking-sphinx-3.1.4/lib/thinking_sphinx/core/index.rb:57:in `render'
/usr/local/lib/ruby/gems/2.1.0/gems/riddle-1.5.12/lib/riddle/configuration.rb:43:in `block in render'
/usr/local/lib/ruby/gems/2.1.0/gems/riddle-1.5.12/lib/riddle/configuration.rb:43:in `collect'
/usr/local/lib/ruby/gems/2.1.0/gems/riddle-1.5.12/lib/riddle/configuration.rb:43:in `render'
/usr/local/lib/ruby/gems/2.1.0/gems/thinking-sphinx-3.1.4/lib/thinking_sphinx/configuration.rb:93:in `render'
/usr/local/lib/ruby/gems/2.1.0/gems/thinking-sphinx-3.1.4/lib/thinking_sphinx/configuration.rb:99:in `block in render_to_file'
/usr/local/lib/ruby/2.1.0/open-uri.rb:36:in `open'
/usr/local/lib/ruby/2.1.0/open-uri.rb:36:in `open'
/usr/local/lib/ruby/gems/2.1.0/gems/thinking-sphinx-3.1.4/lib/thinking_sphinx/configuration.rb:99:in `render_to_file'
/usr/local/lib/ruby/gems/2.1.0/gems/thinking-sphinx-3.1.4/lib/thinking_sphinx/rake_interface.rb:24:in `configure'
/usr/local/lib/ruby/gems/2.1.0/gems/thinking-sphinx-3.1.4/lib/thinking_sphinx/rake_interface.rb:35:in `index'
/usr/local/lib/ruby/gems/2.1.0/gems/thinking-sphinx-3.1.4/lib/thinking_sphinx/tasks.rb:9:in `block (2 levels) in <top (required)>'
/usr/local/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/task.rb:240:in `call'
/usr/local/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/task.rb:240:in `block in execute'
/usr/local/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/task.rb:235:in `each'
/usr/local/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/task.rb:235:in `execute'
/usr/local/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/task.rb:179:in `block in invoke_with_call_chain'
/usr/local/lib/ruby/2.1.0/monitor.rb:211:in `mon_synchronize'
/usr/local/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/task.rb:172:in `invoke_with_call_chain'
/usr/local/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/task.rb:165:in `invoke'
/usr/local/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:150:in `invoke_task'
/usr/local/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:106:in `block (2 levels) in top_level'
/usr/local/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:106:in `each'
/usr/local/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:106:in `block in top_level'
/usr/local/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:115:in `run_with_threads'
/usr/local/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:100:in `top_level'
/usr/local/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:78:in `block in run'
/usr/local/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:176:in `standard_exception_handling'
/usr/local/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:75:in `run'
/usr/local/lib/ruby/gems/2.1.0/gems/rake-10.4.2/bin/rake:33:in `<top (required)>'
/usr/local/bin/rake:23:in `load'
/usr/local/bin/rake:23:in `<main>'
Tasks: TOP => ts:index

**Comment by congkinh** [comment] 2015-08-15 15:34
From my understanding, you should do the following steps (it worked with me on Debian):

```
1. Initialize your database: bundle exec rake RAILS_ENV=production db:schema:load
2. Precompile the assets: bundle exec rake assets:precompile
3. Run Sphinx index: bundle exec rake RAILS_ENV=production ts:index
4. Start the Sphinx daemon: bundle exec rake RAILS_ENV=production ts:start
5. Invoke the delayed job worker: bundle exec rake RAILS_ENV=production jobs:work
6. In a new console, open the project root folder and start the server: bundle exec rails server -e production
```

I guess there would be some errors while documenting the instruction.

**Comment by 419371274** [comment] 2015-08-17 13:54
i follow your instruction,but still the same error occured as above.

**Comment by rap1ds** [comment] 2015-08-18 05:55
Hi! It seems that you are using Ubuntu, right? Sharetribe.com is hosted on Heroku, and I not familiar with running Sharetribe on other environment than Heroku. However, I know that many open-source developers are running Sharetribe on Ubuntu, so I help some one can help you.

My gut feeling is that this error is probably something related to your envrionment and not a bug in Sharetribe code. Because of that, I'll close the issue, but feel free to continue discussion here. If you find out it actually is a bug in Sharetribe code, please open a new issue with clear steps to reproduce the issue. Thanks!

**Closed by rap1ds** 2015-08-18 05:55 UTC

**Comment by svallory** [comment] 2015-08-26 04:24
@419371274 Did you `bundle install`?
