### ISSUE TITLE
Display Bug on Google Maps [object Object]

### ISSUE THREAD

**Issue by dwidoo** [sharetribe/sharetribe#2884] opened 2017-03-01 18:37 UTC
_Please add only one problem per Issue. If you are facing multiple problems, add multiple Issues._

##### Sharetribe Version:
Installed version is 5.7

##### Server mode:

production mode

##### Description:
On the google map, on locations with a unique listing, there is the label `[object Object]` above the red pin.
When there are 2 listings on a specific location, there is the blue circle and no issue.
Any idea to fix this please?

![capture d ecran 2017-03-01 a 19 36 21](https://cloud.githubusercontent.com/assets/4923210/23475048/6575eb3c-feb6-11e6-8faf-13bb6b5b622b.jpg)

**Comment by rap1ds** [comment] 2017-03-02 07:34
Thanks for reporting the issue!

Have you tried a newer Sharetribe version?

My version is:

```
➜  sharetribe git:(master) cat VERSION
6.1.0
➜  sharetribe git:(master) git rev-parse HEAD
8139d92c778b8dc8c8a8a13fdbbf6634a836a827
```

...and I'm running on Mac OSX in development mode, and I can't reproduce the issue:

![screen shot 2017-03-02 at 9 28 36](https://cloud.githubusercontent.com/assets/429876/23497335/427d1892-ff2b-11e6-985d-59c118bd1d11.png)

Also, I can't reproduce this issue on hosted sharetribe.com: https://aalto.sharetribe.com/en/?view=map

**Comment by rap1ds** [comment] 2017-03-02 07:35
Discussion on Community forum: https://www.sharetribe.com/community/t/display-bug-on-the-map/491

**Comment by dwidoo** [comment] 2017-03-02 10:22
hey
Unfortunately I cannot update easily to newer version , because of a payment method integrated.

**Comment by sachinsonugupta** [comment] 2017-03-08 07:45
I have same issue on google map, which files needs to be change for fix this issue in old version, Because i integrated payment method so cannot update to newer version. Can you please direct us to the commit which fixed this issue?

**Comment by rap1ds** [comment] 2017-03-08 08:02
@dwidoo @sachinsonugupta I can't recall what was the exact commit that fixed this. I'd start by looking at the latest changes in [googlemaps.js](https://github.com/sharetribe/sharetribe/blob/master/app/assets/javascripts/googlemaps.js) and [markerclusterer.js.erb](https://github.com/sharetribe/sharetribe/blob/master/app/assets/javascripts/markerclusterer.js.erb)

**Comment by rap1ds** [comment] 2017-03-08 08:03
I'm closing this issue now, because it has been already fixed in the newest version.

Feel free to continue discussion in this thread.

**Closed by rap1ds** 2017-03-08 08:03 UTC
Labels: more information needed

**Comment by dwidoo** [comment] 2017-03-08 21:19
To fix this bug, modify this file : app/assets/javascripts/markerclusterer.js.erb
as shown [here](https://github.com/sharetribe/sharetribe/commit/dd53f85c5e9c534d32837846d5321eb9dcec3a2d#diff-d0801093fe4c1eb3ba614984eb565013)

Thank you @rap1ds for pointing us in the right direction
