### ISSUE TITLE
What software you guys use in production env?

### ISSUE THREAD

**Issue by 1c7** [sharetribe/sharetribe#2525] opened 2016-09-09 11:17 UTC
## What thing you guys use in production env?
AWS? Linode? Heroku? Digital Ocean? or...?
Nginx + Puma? or Unicorn? or Thin? __Passenger?__
Using Docker? (There a Dockerfile)
Deploy via Mina? Capistrano? (There are a Capfile)

## Tech Stack detail
Can you guys put a Tech Stack list in README?
like: Ruby on Rails 4.2.6 + MySQL + Webpack + React...... + RSpec for test + Capistrano for deploy...

## Why open source
you guys should put the [Why open source](https://medium.com/learnings-in-and-around-sharetribe/why-sharetribe-is-open-source-9462384a2f81#.sgpf4dbgt) article in readme

## Image host?
CloudFront or ?

Thank you very much :smile:

**Comment by 1c7** [comment] 2016-09-10 11:31
## Missing image?
There are no example missing.png file in Github Repo
![image](https://cloud.githubusercontent.com/assets/1804755/18410171/300443aa-778d-11e6-85a1-4dad39890531.png)

**Comment by rap1ds** [comment] 2016-09-13 08:19
In production we use: Heroku, Passenger, not using Docker currently (it's actually outdated experimental file), [custom deploy script](https://github.com/sharetribe/sharetribe/blob/master/lib/tasks/deploy.rake) and Amazon S3 for images.

I'm closing this issue now because it's not an issue in the Sharetribe code. I'm happy to continue the discussion about production hosting at the [Community Forum](https://www.sharetribe.com/community)

Please open another issue about this missing.png file with proper steps to reproduce the issue with a clean Sharetribe installation.

**Closed by rap1ds** 2016-09-13 08:19 UTC

**Comment by 1c7** [comment] 2016-09-13 08:31
@rap1ds Thank you
