### ISSUE TITLE
[Docker] npm err elifecycle

### ISSUE THREAD

**Issue by iBicha** [sharetribe/sharetribe#2901] opened 2017-03-15 16:54 UTC
##### Sharetribe Version:

c5071be

##### Environment:

Ubuntu 14.04, Digital Ocean, Docker 17.03.0-ce on 14.04
1GB RAM/CPU/30GB disk

##### Description:

docker build fails to create an image, is stuck on an NPM err ELIFECYCLE

##### Steps To Reproduce:

1-git clone
2-cd into it
3-`docker build -t sharetribe-image .`

Expected result: a built docker image

Actual result: NPM err ELIFECYCLE

##### Additional information

originally i was trying to build jarvisjohnson's (with stripe) but that's another story.

Any instructions on how to deploy sharestripe to production through docker would be nice

**Comment by bladealslayer** [comment] 2017-03-24 07:47
@iBicha, I can't reproduce this. Could you paste build output?

The docker support is quite limited at the moment. Notably, sphinx search is not supported in docker, so you can't run fully functional marketplace like this yet, without some customization of the docker image and the containers you run from it.

**Comment by xuanus** [comment] 2017-04-19 04:42
@bladealslayer Could you please provide more detail on how to get fully supported in docker? What customization needs to be done? Thank you.

**Comment by bladealslayer** [comment] 2017-04-19 10:28
@xuanus as I wrote above, sphinx search is not added and some workarounds are needed to do so, because of how sphinx stores data (needs to be shared between app and worker containers, IIRC). The Docker support is now geared towards Discovery (our yet-to-be-open-sources search service). See more here https://www.sharetribe.com/community/t/location-search/348.

**Comment by bladealslayer** [comment] 2017-04-19 10:29
Closing this as this sounds like temporary issue and did not get any further information.

**Closed by bladealslayer** 2017-04-19 10:29 UTC
Labels: more information needed
