### ISSUE TITLE
Currency Option NOT Available in Listing Field & Filters

### ISSUE THREAD

**Issue by pcm211** [sharetribe/sharetribe#2458] opened 2016-08-25 22:02 UTC
##### Description:
Problem 1:  On changing the hierarchy of Price in the listing .... the shipping & Pickup option vanishes and cannot be reproduced again 
Problem 2:  Currency Option as a Field type NOT Available
Problem 3:  New Filters which are made cannot move above predefined filters to same original location placehoders

##### Steps To Reproduce:
Change Hierarchy of Price etc and pickup & Shipping vanish

Expected result:  Shipping and Pickup should be reproducible

Actual result: Above vanishes

##### Additional information

IF A CURRENCY FIELD TYPE COULD BE ADDED

**Comment by rap1ds** [comment] 2016-08-26 06:32
Thanks for reporting! I'm not sure if I understood everything correctly so if I misunderstood something, feel free to correct me. If you're able to upload a screenshot, that would help a lot!

Your talking about Shipping & Pickup, so I was wondering, are you using PayPal as a payment gateway?

Problem 1: In Order Types page, if you disable the option "Allow sellers to add a price to their listings", the shipping and pickup options are not available. That's by design. Shipping address is provided by PayPal, so if there's no price -> PayPal payment will not be used -> No shipping.

Problem 2: Adding support for multiple currencies in one marketplace is not in our near term roadmap. Taking into account all the complexity coming from payment gateways, it's a bit tricky to add.

Problem 3: That's right, you can't move the predefined filters nor can you move new filters above the predefined once. That's a known issue, but it's not in our near term plans to change this.

I'm closing this issue now but feel free to continue discussion in this thread.

**Closed by rap1ds** 2016-08-26 06:32 UTC

**Comment by pcm211** [comment] 2016-08-26 16:40
@rap1ds ... 
Your talking about Shipping & Pickup, so I was wondering, are you using PayPal as a payment gateway?

Ans: No I just want to keep these fields (Shipping & Pickup) as information posted by sellers  .. i do not intend to use a Payment Gateway option 

PROBLEM 1. Even after ticking under the Pricing & checkout ----  Allow sellers to add a price to their listings the option of shipping and pickup does NOT Reappear

PROBLEM 2 : If problem 1 is a bug then an interim solution can be implemented with the CURRENCY Suffix and the reqmt of Multi currency was not asked for ( eg --- Type Currency ... input Numeric digits with automatic Suffix as $/ any currency picked from Database of communities)
