### ISSUE TITLE
wefunder type features ?

### ISSUE THREAD

**Issue by niccolox** [sharetribe/sharetribe#2402] opened 2016-08-13 22:44 UTC
hi

am interested in extensions for wefunder type features

i.e. https://en.wikipedia.org/wiki/Wefunder#cite_note-nyt-3

crowd sourced equity based kick starts

thoughts?

**Comment by rap1ds** [comment] 2016-08-23 17:29
Hi @niccolox! Thanks for the suggestion. This is not in the development roadmap right now, so we don't have plans to implement features supporting crowd funding features.

I'm closing this issue now because it's not a bug in the Sharetribe code. Feel free to continue the discussion in this thread or in the [Community Forum](https://www.sharetribe.com/community/)

**Closed by rap1ds** 2016-08-23 17:29 UTC
