### ISSUE TITLE
Cannot load to the main page(500 Internal Server Error) 

### ISSUE THREAD

**Issue by kikyou0797** [sharetribe/sharetribe#1647] opened 2016-01-18 01:26 UTC
I am trying to deploy Sharetribe on aws(with RDS and S3), and set everything by following this tutorial.
http://www.pequi.eu/installation-de-sharetribe-sur-amazon-web-services-aws-etape-1-configuration-daws/

Everything worked fine during the configuration, and set up page showed up with no problem.
But after clicking the save changes button,  500 Internal Server Error and such log came out. 

Could anyone please give me a clue to solve this?
-------------
127.0.0.1:11211 failed (count: 0)

127.0.0.1:11211 failed (count: 0)

DalliError: No server available

DalliError: No server available

127.0.0.1:11211 failed (count: 1)

127.0.0.1:11211 failed (count: 1)

127.0.0.1:11211 is down

127.0.0.1:11211 is down

DalliError: No server available

DalliError: No server available

{"method":"GET","path":"/","format":"html","controller":"homepage","action":"index","status":500,"error":"ArgumentError: Cannot find translation for marketplace name community_id: 1, locale: zh","duration":2892.27,"params":{},"host":null,"community_id":null,"current_user_id":null,"request_uuid":null}

{"method":"GET","path":"/","format":"html","controller":"homepage","action":"index","status":500,"error":"ArgumentError: Cannot find translation for marketplace name community_id: 1, locale: zh","duration":2892.27,"params":{},"host":null,"community_id":null,"current_user_id":null,"request_uuid":null}

ArgumentError (Cannot find translation for marketplace name community_id: 1, locale: zh):

  app/models/community.rb:292:in `name'

  app/helpers/application_helper.rb:469:in `service_name'

  app/controllers/application_controller.rb:102:in `set_locale'

  lib/rack_middleware/custom_domain_cookie.rb:20:in `call'

ArgumentError (Cannot find translation for marketplace name community_id: 1, locale: zh):

  app/models/community.rb:292:in `name'

  app/helpers/application_helper.rb:469:in `service_name'

  app/controllers/application_controller.rb:102:in `set_locale'

  lib/rack_middleware/custom_domain_cookie.rb:20:in `call'

and a lots of log...
-------------

**Comment by rap1ds** [comment] 2016-01-19 08:45
Hi, thanks for reporting the issue! This feels like a bug in codebase.

You are seeing the error because there's no Chinese (zh) translations for the marketplace name.

Could you post exact steps how to reproduce the issue? How did you ended up in the situation where the translation is missing?

**Comment by kikyou0797** [comment] 2016-01-19 10:59
Thank you for the reply! 
I configured the environment in AWS, and entered the set up page. Then selected Chinese in the marketplace language. Click save change and the error came out.

Now I reset the server and try to configure the server one more time.  Wish everything goes fine when I select English as my default language.

**Comment by kikyou0797** [comment] 2016-01-20 01:45
It works when I reset the language to EN then.  I can access my site now!
Cheers!

I need it to be in JP after all though, it is really a great first step for me.

**Comment by rap1ds** [comment] 2016-01-20 06:51
Ok, good to know, so apparently there's a bug with Chinese.

**Comment by rap1ds** [comment] 2016-02-22 13:24
Tried to reproduce this. I was able to create a marketplace in Chinese. So the issue is probably somewhere else. At the moment I don't know how to reproduce this, so I'm closing the tickets.

If you have any tips how to reproduce, feel free to post them to this thread.

**Closed by rap1ds** 2016-02-22 13:24 UTC
Labels: bug

**Comment by 7kashy** [comment] 2018-05-01 10:46
Getting similar error:

- -> /
127.0.0.1:11211 failed (count: 7) Errno::ECONNREFUSED: Connection refused - connect(2) for "127.0.0.1" port 11211
DalliError: No server available
DalliError: No server available
DalliError: No server available
DalliError: No server available
{"method":"GET","path":"/","format":"html","controller":"HomepageController","action":"index","status":500,"error":"ActionView::Template::Error: The asset \"sharetribe_icon.png\" is not present in the asset pipeline.","duration":49.13,"view":0.0,"db":8.25,"params":{},"host":"159.203.15.20","community_id":1,"current_user_id":"","user_agent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_4) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/11.1 Safari/605.1.15","referer":"","forwarded_for":"","request_uuid":"8c9b9591-549f-4142-b59d-e82519d1b1ac"}
  
ActionView::Template::Error (The asset "sharetribe_icon.png" is not present in the asset pipeline.):
    30:   - if @current_community.logo?
    31:     - meta_image = @current_community.logo.url(:original)
    32:   - else
    33:     - meta_image = image_path("sharetribe_icon.png")
    34: 
    35: %title= title
    36: %meta{ :property => "og:title", :content => title}
  
app/views/layouts/_marketplace_head.haml:33:in `_app_views_layouts__marketplace_head_haml__1658464820369287881_73240600'
app/views/layouts/_head.haml:28:in `_app_views_layouts__head_haml___144193079704303512_74320560'
app/views/layouts/application.haml:1:in `_app_views_layouts_application_haml___111408097996604989_81350220'
app/controllers/homepage_controller.rb:128:in `block in index'
app/services/result.rb:70:in `on_success'
app/controllers/homepage_controller.rb:126:in `index'
lib/rack_middleware/session_context_middleware.rb:15:in `call'
lib/rack_middleware/marketplace_lookup.rb:33:in `call'
lib/rack_middleware/custom_cookie_renamer.rb:11:in `call'
lib/rack_middleware/enforce_ssl.rb:23:in `call'
lib/rack_middleware/health_check.rb:12:in `call'
{"method":"GET","path":"/500","format":"html","controller":"ErrorsController","action":"server_error","status":500,"error":"ActionView::Template::Error: The asset \"favicon.ico\" is not present in the asset pipeline.","duration":6.37,"view":0.0,"db":0.06,"params":{},"host":null,"community_id":null,"current_user_id":null,"user_agent":null,"referer":null,"forwarded_for":null,"request_uuid":null}
Error during failsafe response: The asset "favicon.ico" is not present in the asset pipeline.
  /home/dev/.rvm/gems/ruby-2.3.4/gems/sprockets-rails-3.2.0/lib/sprockets/rails/helper.rb:83:in `compute_asset_path'
  /home/dev/.rvm/gems/ruby-2.3.4/gems/actionview-5.1.1/lib/action_view/helpers/asset_url_helper.rb:198:in `asset_path'
  /home/dev/sharetribe/app/models/community.rb:243:in `block in <class:Community>'
  /home/dev/.rvm/gems/ruby-2.3.4/gems/paperclip-5.1.0/lib/paperclip/url_generator.rb:26:in `default_url'
  /home/dev/.rvm/gems/ruby-2.3.4/gems/paperclip-5.1.0/lib/paperclip/url_generator.rb:36:in `most_appropriate_url'
  /home/dev/.rvm/gems/ruby-2.3.4/gems/delayed_paperclip-3.0.1/lib/delayed_paperclip/url_generator.rb:38:in `most_appropriate_url'
  /home/dev/.rvm/gems/ruby-2.3.4/gems/delayed_paperclip-3.0.1/lib/delayed_paperclip/url_generator.rb:12:in `for'
  /home/dev/.rvm/gems/ruby-2.3.4/gems/paperclip-5.1.0/lib/paperclip/attachment.rb:146:in `url'
  /home/dev/.rvm/gems/ruby-2.3.4/gems/paperclip-5.1.0/lib/paperclip/attachment.rb:187:in `to_s'
  /home/dev/.rvm/gems/ruby-2.3.4/gems/actionview-5.1.1/lib/action_view/buffers.rb:12:in `<<'
  /home/dev/sharetribe/app/views/layouts/blank_layout.erb:78:in `block in _app_views_layouts_blank_layout_erb__404338842248585446_69371780'
  /home/dev/.rvm/gems/ruby-2.3.4/gems/possibly-1.0.1/lib/possibly.rb:6:in `each'
  /home/dev/.rvm/gems/ruby-2.3.4/gems/possibly-1.0.1/lib/possibly.rb:6:in `block (2 levels) in <class:Maybe>'
  /home/dev/sharetribe/app/views/layouts/blank_layout.erb:77:in `_app_views_layouts_blank_layout_erb__404338842248585446_69371780'
  /home/dev/.rvm/gems/ruby-2.3.4/gems/actionview-5.1.1/lib/action_view/template.rb:157:in `block in render'
  /home/dev/.rvm/gems/ruby-2.3.4/gems/activesupport-5.1.1/lib/active_support/notifications.rb:166:in `block in instrument'
  /home/dev/.rvm/gems/ruby-2.3.4/gems/activesupport-5.1.1/lib/active_support/notifications/instrumenter.rb:21:in `instrument'
  /home/dev/.rvm/gems/ruby-2.3.4/gems/activesupport-5.1.1/lib/active_support/notifications.rb:166:in `instrument'
  /home/dev/.rvm/gems/ruby-2.3.4/gems/actionview-5.1.1/lib/action_view/template.rb:352:in `instrument_render_template'
  /home/dev/.rvm/gems/ruby-2.3.4/gems/actionview-5.1.1/lib/action_view/template.rb:155:in `render'
  /home/dev/.rvm/gems/ruby-2.3.4/gems/actionview-5.1.1/lib/action_view/renderer/template_renderer.rb:64:in `render_with_layout'
  /home/dev/.rvm/gems/ruby-2.3.4/gems/actionview-5.1.1/lib/action_view/renderer/template_renderer.rb:50:in `render_template'
  /home/dev/.rvm/gems/ruby-2.3.4/gems/actionview-5.1.1/lib/action_view/renderer/template_renderer.rb:14:in `render'
  /home/dev/.rvm/gems/ruby-2.3.4/gems/actionview-5.1.1/lib/action_view/renderer/renderer.rb:42:in `render_template'
  /home/dev/.rvm/gems/ruby-2.3.4/gems/actionview-5.1.1/lib/action_view/renderer/renderer.rb:23:in `render'
  /home/dev/.rvm/gems/ruby-2.3.4/gems/actionview-5.1.1/lib/action_view/rendering.rb:103:in `_render_template'
  /home/dev/.rvm/gems/ruby-2.3.4/gems/actionpack-5.1.1/lib/action_controller/metal/streaming.rb:217:in `_render_template'
  /home/dev/.rvm/gems/ruby-2.3.4/gems/actionview-5.1.1/lib/action_view/rendering.rb:83:in `render_to_body'
  /home/dev/.rvm/gems/ruby-2.3.4/gems/actionpack-5.1.1/lib/action_controller/metal/rendering.rb:52:in `render_to_body'
  /home/dev/.rvm/gems/ruby-2.3.4/gems/actionpack-5.1.1/lib/action_controller/metal/renderers.rb:141:in `render_to_body'
  /home/dev/.rvm/gems/ruby-2.3.4/gems/actionpack-5.1.1/lib/abstract_controller/rendering.rb:24:in `render'
  /home/dev/.rvm/gems/ruby-2.3.4/gems/actionpack-5.1.1/lib/action_controller/metal/rendering.rb:36:in `render'
  /home/dev/.rvm/gems/ruby-2.3.4/gems/actionpack-5.1.1/lib/action_controller/metal/instrumentation.rb:44:in `block (2 levels) in render'
  /home/dev/.rvm/gems/ruby-2.3.4/gems/activesupport-5.1.1/lib/active_support/core_ext/benchmark.rb:12:in `block in ms'
  /home/dev/.rvm/rubies/ruby-2.3.4/lib/ruby/2.3.0/benchmark.rb:308:in `realtime'
  /home/dev/.rvm/gems/ruby-2.3.4/gems/activesupport-5.1.1/lib/active_support/core_ext/benchmark.rb:12:in `ms'
  /home/dev/.rvm/gems/ruby-2.3.4/gems/actionpack-5.1.1/lib/action_controller/metal/instrumentation.rb:44:in `block in render'
  /home/dev/.rvm/gems/ruby-2.3.4/gems/actionpack-5.1.1/lib/action_controller/metal/instrumentation.rb:87:in `cleanup_view_runtime'
  /home/dev/.rvm/gems/ruby-2.3.4/gems/activerecord-5.1.1/lib/active_record/railties/controller_runtime.rb:29:in `cleanup_view_runtime'
  /home/dev/.rvm/gems/ruby-2.3.4/gems/actionpack-5.1.1/lib/action_controller/metal/instrumentation.rb:43:in `render'
  /home/dev/sharetribe/app/controllers/errors_controller.rb:10:in `server_error'
  /home/dev/.rvm/gems/ruby-2.3.4/gems/actionpack-5.1.1/lib/action_controller/metal/basic_implicit_render.rb:4:in `send_action'
  /home/dev/.rvm/gems/ruby-2.3.4/gems/actionpack-5.1.1/lib/abstract_controller/base.rb:186:in `process_action'
  /home/dev/.rvm/gems/ruby-2.3.4/gems/actionpack-5.1.1/lib/action_controller/metal/rendering.rb:30:in `process_action'
  /home/dev/.rvm/gems/ruby-2.3.4/gems/actionpack-5.1.1/lib/abstract_controller/callbacks.rb:20:in `block in process_action'
  /home/dev/.rvm/gems/ruby-2.3.4/gems/activesupport-5.1.1/lib/active_support/callbacks.rb:131:in `run_callbacks'
  /home/dev/.rvm/gems/ruby-2.3.4/gems/actionpack-5.1.1/lib/abstract_controller/callbacks.rb:19:in `process_action'
  /home/dev/.rvm/gems/ruby-2.3.4/gems/actionpack-5.1.1/lib/action_controller/metal/rescue.rb:20:in `process_action'
  /home/dev/.rvm/gems/ruby-2.3.4/gems/actionpack-5.1.1/lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
  /home/dev/.rvm/gems/ruby-2.3.4/gems/activesupport-5.1.1/lib/active_support/notifications.rb:166:in `block in instrument'
  /home/dev/.rvm/gems/ruby-2.3.4/gems/activesupport-5.1.1/lib/active_support/notifications/instrumenter.rb:21:in `instrument'
  /home/dev/.rvm/gems/ruby-2.3.4/gems/activesupport-5.1.1/lib/active_support/notifications.rb:166:in `instrument'
  /home/dev/.rvm/gems/ruby-2.3.4/gems/actionpack-5.1.1/lib/action_controller/metal/instrumentation.rb:30:in `process_action'
  /home/dev/.rvm/gems/ruby-2.3.4/gems/actionpack-5.1.1/lib/action_controller/metal/params_wrapper.rb:252:in `process_action'
  /home/dev/.rvm/gems/ruby-2.3.4/gems/activerecord-5.1.1/lib/active_record/railties/controller_runtime.rb:22:in `process_action'
  /home/dev/.rvm/gems/ruby-2.3.4/gems/actionpack-5.1.1/lib/abstract_controller/base.rb:124:in `process'
  /home/dev/.rvm/gems/ruby-2.3.4/gems/actionview-5.1.1/lib/action_view/rendering.rb:30:in `process'
  /home/dev/.rvm/gems/ruby-2.3.4/gems/actionpack-5.1.1/lib/action_controller/metal.rb:189:in `dispatch'
  /home/dev/.rvm/gems/ruby-2.3.4/gems/actionpack-5.1.1/lib/action_controller/metal.rb:253:in `dispatch'
  /home/dev/.rvm/gems/ruby-2.3.4/gems/actionpack-5.1.1/lib/action_dispatch/routing/route_set.rb:49:in `dispatch'
  /home/dev/.rvm/gems/ruby-2.3.4/gems/actionpack-5.1.1/lib/action_dispatch/routing/route_set.rb:31:in `serve'
  /home/dev/.rvm/gems/ruby-2.3.4/gems/actionpack-5.1.1/lib/action_dispatch/journey/router.rb:46:in `block in serve'
  /home/dev/.rvm/gems/ruby-2.3.4/gems/actionpack-5.1.1/lib/action_dispatch/journey/router.rb:33:in `each'
  /home/dev/.rvm/gems/ruby-2.3.4/gems/actionpack-5.1.1/lib/action_dispatch/journey/router.rb:33:in `serve'
  /home/dev/.rvm/gems/ruby-2.3.4/gems/actionpack-5.1.1/lib/action_dispatch/routing/route_set.rb:832:in `call'
  /home/dev/.rvm/gems/ruby-2.3.4/gems/actionpack-5.1.1/lib/action_dispatch/middleware/show_exceptions.rb:49:in `render_exception'
  /home/dev/.rvm/gems/ruby-2.3.4/gems/actionpack-5.1.1/lib/action_dispatch/middleware/show_exceptions.rb:34:in `rescue in call'
  /home/dev/.rvm/gems/ruby-2.3.4/gems/actionpack-5.1.1/lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
  /home/dev/.rvm/gems/ruby-2.3.4/gems/newrelic_rpm-4.2.0.334/lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
  /home/dev/.rvm/gems/ruby-2.3.4/gems/lograge-0.5.1/lib/lograge/rails_ext/rack/logger.rb:15:in `call_app'
  /home/dev/.rvm/gems/ruby-2.3.4/gems/railties-5.1.1/lib/rails/rack/logger.rb:24:in `block in call'
  /home/dev/.rvm/gems/ruby-2.3.4/gems/activesupport-5.1.1/lib/active_support/tagged_logging.rb:69:in `block in tagged'
  /home/dev/.rvm/gems/ruby-2.3.4/gems/activesupport-5.1.1/lib/active_support/tagged_logging.rb:26:in `tagged'
  /home/dev/.rvm/gems/ruby-2.3.4/gems/activesupport-5.1.1/lib/active_support/tagged_logging.rb:69:in `tagged'
  /home/dev/.rvm/gems/ruby-2.3.4/gems/railties-5.1.1/lib/rails/rack/logger.rb:24:in `call'
  /home/dev/.rvm/gems/ruby-2.3.4/gems/newrelic_rpm-4.2.0.334/lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
  /home/dev/.rvm/gems/ruby-2.3.4/gems/actionpack-5.1.1/lib/action_dispatch/middleware/remote_ip.rb:79:in `call'
  /home/dev/.rvm/gems/ruby-2.3.4/gems/newrelic_rpm-4.2.0.334/lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
  /home/dev/.rvm/gems/ruby-2.3.4/gems/request_store-1.3.2/lib/request_store/middleware.rb:9:in `call'
  /home/dev/.rvm/gems/ruby-2.3.4/gems/newrelic_rpm-4.2.0.334/lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
  /home/dev/.rvm/gems/ruby-2.3.4/gems/actionpack-5.1.1/lib/action_dispatch/middleware/request_id.rb:25:in `call'
  /home/dev/.rvm/gems/ruby-2.3.4/gems/newrelic_rpm-4.2.0.334/lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
  /home/dev/.rvm/gems/ruby-2.3.4/gems/rack-2.0.3/lib/rack/method_override.rb:22:in `call'
  /home/dev/.rvm/gems/ruby-2.3.4/gems/newrelic_rpm-4.2.0.334/lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
  /home/dev/.rvm/gems/ruby-2.3.4/gems/rack-2.0.3/lib/rack/runtime.rb:22:in `call'
  /home/dev/.rvm/gems/ruby-2.3.4/gems/newrelic_rpm-4.2.0.334/lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
  /home/dev/.rvm/gems/ruby-2.3.4/gems/activesupport-5.1.1/lib/active_support/cache/strategy/local_cache_middleware.rb:27:in `call'
  /home/dev/.rvm/gems/ruby-2.3.4/gems/newrelic_rpm-4.2.0.334/lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
  /home/dev/.rvm/gems/ruby-2.3.4/gems/actionpack-5.1.1/lib/action_dispatch/middleware/executor.rb:12:in `call'
  /home/dev/.rvm/gems/ruby-2.3.4/gems/newrelic_rpm-4.2.0.334/lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
  /home/dev/.rvm/gems/ruby-2.3.4/gems/actionpack-5.1.1/lib/action_dispatch/middleware/static.rb:125:in `call'
  /home/dev/.rvm/gems/ruby-2.3.4/gems/newrelic_rpm-4.2.0.334/lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
  /home/dev/.rvm/gems/ruby-2.3.4/gems/rack-2.0.3/lib/rack/sendfile.rb:111:in `call'
  /home/dev/.rvm/gems/ruby-2.3.4/gems/newrelic_rpm-4.2.0.334/lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
  /home/dev/sharetribe/lib/rack_middleware/enforce_ssl.rb:23:in `call'
  /home/dev/.rvm/gems/ruby-2.3.4/gems/newrelic_rpm-4.2.0.334/lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
  /home/dev/sharetribe/lib/rack_middleware/health_check.rb:12:in `call'
  /home/dev/.rvm/gems/ruby-2.3.4/gems/newrelic_rpm-4.2.0.334/lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
  /home/dev/.rvm/gems/ruby-2.3.4/gems/railties-5.1.1/lib/rails/engine.rb:522:in `call'
  /home/dev/.rvm/gems/ruby-2.3.4/gems/railties-5.1.1/lib/rails/railtie.rb:185:in `public_send'
  /home/dev/.rvm/gems/ruby-2.3.4/gems/railties-5.1.1/lib/rails/railtie.rb:185:in `method_missing'
  /home/dev/.rvm/gems/ruby-2.3.4/gems/newrelic_rpm-4.2.0.334/lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
  /home/dev/.rvm/gems/ruby-2.3.4/gems/rack-2.0.3/lib/rack/deflater.rb:34:in `call'
  /home/dev/.rvm/gems/ruby-2.3.4/gems/newrelic_rpm-4.2.0.334/lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call'
  /home/dev/.rvm/gems/ruby-2.3.4/gems/rack-2.0.3/lib/rack/handler/webrick.rb:86:in `service'
  /home/dev/.rvm/rubies/ruby-2.3.4/lib/ruby/2.3.0/webrick/httpserver.rb:140:in `service'
  /home/dev/.rvm/rubies/ruby-2.3.4/lib/ruby/2.3.0/webrick/httpserver.rb:96:in `run'
  /home/dev/.rvm/rubies/ruby-2.3.4/lib/ruby/2.3.0/webrick/server.rb:296:in `block in start_thread'

Any ideas?
