### ISSUE TITLE
After customizing cover images on s3, assets, particularly fonts, are not served from s3

### ISSUE THREAD

**Issue by thefoodcorridor** [sharetribe/sharetribe#1849] opened 2016-03-28 14:47 UTC
##### Sharetribe Version:

07825deab4d58b438641ad5f1a3de1b478babaeb

##### Environment:

Heroku

##### Server mode:

Production

##### Description:

When I customize the cover images using the admin screen, and have my assets served from s3, the `public/assets` directory is not pushed to s3, and in particular the fonts are not.  

To be honest, this may have happened when I set up s3 initially and I may have missed it, but am not sure about that.  (In other words, updating the cover images may not have caused this.)

##### Steps To Reproduce:

1. Install sharetribe on heroku with an s3_bucket_name and s3_upload_bucket_name in the production config.
1. Visit site, everything should be fine.
1. Install a new custom cover image.
1. Visit site, you should see issues like this, where the search, grid, map and list icons are all replaced with squares.

![sharetribe-icon-issues](https://cloud.githubusercontent.com/assets/17932171/14079886/70c747f4-f4be-11e5-9683-ca54015ebbc8.png)

If you look in the devtools, you can see that a number of assets are not available:
   * /assets/modernizr.min-799bf3857c6ec71e5491c8f6e9faa935.js
   * /assets/application-741029e8014a31147bdf6160d7fbc0ee.js
   * /assets/fontawesome-webfont-00022e35cd0adcdcaf29550c7d8b4460.woff?v=3.0.1

There are more

I also tried setting the asset host to the s3 bucket url: https://xxx.s3.amazonaws.com  

Expected result: Assets are pushed to s3

Actual result: Assets are not pushed to s3

##### Additional information

May be related to https://github.com/sharetribe/sharetribe/issues/1824  After reading through that thread, I realize I can manually push the assets to s3, or use a CDN, but am looking for guidance on how to accomplish that without the `asset_sync` gem.

**Comment by mooreds** [comment] 2016-03-29 14:32
@rap1ds Do you have any guidance on how to get assets pushed up to s3 and then served from there?

Because unfortunately the issue is bigger than just fonts--it's all javascript.

**Comment by rap1ds** [comment] 2016-03-29 14:55
Hi! Thanks for reporting the issue.

This bug report is partially incorrect: It **is expected** that assets (excluding user-generated content) are **not** pushed to S3. There's no need to do that. Better option than serving assets from S3 is to serve them from Rails server and configure CDN.

On the other hand, it is **not expected** that the fonts are broken. I hope #1850 will fix that.

Here are two Heroku guides worth reading:

* [Please Do Not Use Asset Sync](https://devcenter.heroku.com/articles/please-do-not-use-asset-sync)
* [Using Amazon CloudFront CDN](https://devcenter.heroku.com/articles/using-amazon-cloudfront-cdn)

I'm closing this issue now because the font part is already covered by #1824 . Feel free to comment on this thread if you have some additional information or if I missed something.

**Closed by rap1ds** 2016-03-29 14:55 UTC
Labels: bug

**Comment by mooreds** [comment] 2016-03-29 14:57
Thanks @rap1ds   I will review those guides.

For anyone else who encounters this issue and wants to back it out, here's how to do so (mostly):

Null out the stylesheet: `update communities set stylesheet_url = null where id = <yourid>;`

And make sure `asset_host` is not set in the environment or your `config.yml`.
