### ISSUE TITLE
Hire someone with Sharetribe knowledge !

### ISSUE THREAD

**Issue by leofreitasusa** [sharetribe/sharetribe#2845] opened 2017-01-02 15:20 UTC
Hello everyone.

I have a selfhosted installation of sharetribe that need some customization.

I am looking to hire someone to do it.

Is there anyone interesting?

Please a-mail me:

laellyson @ icloud.com

**Comment by pcm211** [comment] 2017-01-03 05:28
@leofreitasusa .. this is a community ..... and most of us are already well employed....we contribute towards a better solution for all .... hope i have helped you out ... :)

**Comment by rap1ds** [comment] 2017-01-09 08:28
Hi @leofreitasusa ! Have a look at our Community Forum. There's for example [this post](https://www.sharetribe.com/community/t/list-of-coding-freelancers-consultants-who-have-done-good-work/207) that is probably exactly what you're looking for.

I'm now closing this issues because this is not a bug report and I think this conversation is better suited for community forum.

**Closed by rap1ds** 2017-01-09 08:28 UTC
