### ISSUE TITLE
Timeout

### ISSUE THREAD

**Issue by rkukuczka** [sharetribe/sharetribe#1169] opened 2015-04-21 07:49 UTC
Hi everybody:
I get sth like this up and then, no many records really, how comes. What can I do about it?

I18n::InvalidLocaleData in HomepageController#index

can not load translations from /Users/rafal/Documents/dev/PRD-EcoHub/Modules/Repos/Bitbucket/EcoHub4/sharetribe_2/config/locales/hu.yml: #<Rack::Timeout::RequestTimeoutError: Request ran for longer than 15 seconds.>

**Comment by rap1ds** [comment] 2015-08-24 06:58
I guess that because you get an `InvalidLocaleData` exception, the issue is that you are using locale that is not available.

We added Hungarian language only recently, so you might want to pull the latest changes and see if that works.

I believe that this is not a bug in the Sharetribe codebase, so that's why I'm closing the issue. If you find out more information or think that this is an issue in the code, we can reopen the issue.

**Closed by rap1ds** 2015-08-24 06:58 UTC
