### ISSUE TITLE
The user does not know that he is now able to post a listing

### ISSUE THREAD

**Issue by dwidoo** [sharetribe/sharetribe#2429] opened 2016-08-19 14:58 UTC
5.8.0
Production mode

I am not sure if this is an issue or a normal behaviour.
When the admin authorizes a user to post a listing, the user is not notified (does not receive an email) that he is now able to post a listing...

**Comment by rap1ds** [comment] 2016-08-19 18:59
Thanks for reporting! You're right, there's no notification at the moment. The admin can of course manually send a message to the user.

Since this is not a bug in the Sharetribe code, I'm closing the issue now but feel free to continue the discussion in this thread.

**Closed by rap1ds** 2016-08-19 18:59 UTC
