### ISSUE TITLE
utf8mb4 support

### ISSUE THREAD

**Issue by kikyou0797** [sharetribe/sharetribe#1685] opened 2016-01-31 10:10 UTC
I'd like sharetribe to support JP or CN by using utf8mb4, 
I set a parameter group in aws rds and make all default setting is utf8mb4

and then I ran the " rake RAILS_ENV=production db:schema:load"

error following came out.  
---
Mysql2::Error: Index column size too large. The maximum column size is 767 bytes.: CREATE UNIQUE INDEX `index_auth_tokens_on_token` USING btree ON `auth_tokens` (`token`) 
---

could you tell me how to let sharetribe support utf8mb4?

**Comment by rap1ds** [comment] 2016-02-01 08:03
Hi @kikyou0797 and thanks for the suggestion! This is something we plan to implement quite soon. It needs some migrations to the database but otherwise it should be too big thing to do.

I'll close the issue since this is not a bug in the Sharetribe code. Feel free to continue the discussion in this thread.

**Closed by rap1ds** 2016-02-01 08:03 UTC
