### ISSUE TITLE
Problem: Setting up Sharetribe for production 

### ISSUE THREAD

**Issue by jimix974** [sharetribe/sharetribe#2527] opened 2016-09-10 16:53 UTC
Hello,

I have a problem after generate the secret key and add it on config.yml

When I create the database, I have an error
_Please add only one problem per Issue. If you are facing multiple problems, add multiple Issues._

SRV:~/sharetribe$ RAILS_ENV=production bundle exec rake db:create
/var/lib/gems/2.3.0/gems/newrelic_rpm-3.9.1.236/lib/new_relic/agent/configuration/default_source.rb:675: warning: key :disable_mongo is duplicated and overwritten on line 987
rake aborted!
**Psych::SyntaxError: (/home/jimix/sharetribe//config/config.yml): could not find expected ':' while scanning a simple key at line 24 column 1**
/home/jimix/sharetribe/config/config_loader.rb:31:in `read_yaml_file'
/home/jimix/sharetribe/config/config_loader.rb:18:in `load_app_config'
/home/jimix/sharetribe/config/application.rb:74:in `<class:Application>'
/home/jimix/sharetribe/config/application.rb:23:in `<module:Kassi>'
/home/jimix/sharetribe/config/application.rb:22:in `<top (required)>'
/home/jimix/sharetribe/Rakefile:4:in `require'
/home/jimix/sharetribe/Rakefile:4:in `<top (required)>'
(See full trace by running task with --trace)

My database is not create.

Why the link : "/home/jimix/sharetribe//config/config.ym"    have 2 backslash ? where can I change it

**Comment by pcm211** [comment] 2016-09-11 02:01
The problem is there in mongo.db... it's got the same code twice ... so Goto line no 675 of 
> /var/lib/gems/2.3.0/gems/newrelic_rpm-3.9.1.236/lib/new_relic/agent/configuration/default_source.rb
> 

Comment the code out which is similar to lines starting from 975 in the same file ... 

Enjoy

**Comment by jimix974** [comment] 2016-09-12 04:58
hello, thanks for your answer
but I had already delete this row

My question is for the following

**Psych::SyntaxError: (/home/jimix/sharetribe//config/config.yml): could not find expected ':' while scanning a simple key at line 24 column 1**
/home/jimix/sharetribe/config/config_loader.rb:31:in read_yaml_file' /home/jimix/sharetribe/config/config_loader.rb:18:inload_app_config'
/home/jimix/sharetribe/config/application.rb:74:in <class:Application>' /home/jimix/sharetribe/config/application.rb:23:inmodule:Kassi'
/home/jimix/sharetribe/config/application.rb:22:in <top (required)>' /home/jimix/sharetribe/Rakefile:4:inrequire'
/home/jimix/sharetribe/Rakefile:4:in `'
(See full trace by running task with --trace)

**Comment by pcm211** [comment] 2016-09-12 05:32
you are using which editor ...

the problem is with leading spaces .... check and redo it with a different
editor
as normal editors do not take enter as leading spaces ...

hope it helps


*Tx & Regards,*


*VIVEK KUMAR BARDIA*72 A,  Bidhan Sarani
3rd Floor,
Kolkata - 700 006

Ph: + 91 - 33 - 25548435 (Kolkata)
     * + 91 - 82 7575 0008 (Pune)*

**Comment by jimix974** [comment] 2016-09-12 05:44
I use "NANO", what is the problem about spaces? I don't understand ..

Why I have  "//" in this error?
Psych::SyntaxError: (/home/jimix/sharetribe**//**config/config.yml): could not find expected ':' while scanning a simple key at line 24 column 1

**Comment by pcm211** [comment] 2016-09-12 05:51
upload lines 20-30 for further expl ... you may like to change the key
before uploading


*Tx & Regards,*


*VIVEK KUMAR BARDIA*72 A,  Bidhan Sarani
3rd Floor,
Kolkata - 700 006

Ph: + 91 - 33 - 25548435 (Kolkata)
     * + 91 - 82 7575 0008 (Pune)*

**Comment by jimix974** [comment] 2016-09-12 12:09
I'm really sorry but I don't understand what do you want I do ...

I generate and set the secrete key. I put it on my config.yml file ... I don't know what is the problem with the key 

Thanks a lot for your help

**Comment by pcm211** [comment] 2016-09-12 12:17
Show us how have you been writing it. ! It looks like a problem of leading and trailing spaces in the file ..

You can just remove the config.yml file and recreate it ...

**Comment by rap1ds** [comment] 2016-09-12 12:43
Based on the error message `Psych::SyntaxError: (/home/jimix/sharetribe//config/config.yml): could not find expected ':' while scanning a simple key at line 24 column 1` it looks like you have an error in you `config.yml` file syntax. The YAML parsed is expecting a colon (`:`), but can't find it. So double check your `config.yml` and make sure it's valid YAML.

I'm closing this issue now because it seems that this is not a bug in the Sharetribe code but a error in the configuration. Also, for installation help and other topics that are not bugs in the Sharetribe code, I recommend you to post a new topic in the community forum https://www.sharetribe.com/community .

**Closed by rap1ds** 2016-09-12 12:43 UTC
