### ISSUE TITLE
delayed_paperclip

### ISSUE THREAD

**Issue by nazrulio** [sharetribe/sharetribe#1466] opened 2015-10-02 16:13 UTC
I have installed sharetribe and try to browse application then it shows:
 NoMethodError - undefined method `[]=' for nil:NilClass:
  delayed_paperclip (2.9.1) lib/delayed_paperclip.rb:52:in `process_in_background'
  app/models/community.rb:204:in `<class:Community>'
  app/models/community.rb:104:in `<top (required)>'
  zeus (0.15.1) lib/zeus/load_tracking.rb:50:in `load'
  activesupport (3.2.21) lib/active_support/dependencies.rb:469:in `block in load_file'
  activesupport (3.2.21) lib/active_support/dependencies.rb:639:in `new_constants_in'
  activesupport (3.2.21) lib/active_support/dependencies.rb:468:in `load_file'
  activesupport (3.2.21) lib/active_support/dependencies.rb:353:in `require_or_load'
  activesupport (3.2.21) lib/active_support/dependencies.rb:502:in `load_missing_constant'
  activesupport (3.2.21) lib/active_support/dependencies.rb:192:in `block in const_missing'
  activesupport (3.2.21) lib/active_support/dependencies.rb:190:in `const_missing'
  activesupport (3.2.21) lib/active_support/dependencies.rb:514:in `load_missing_constant'
  activesupport (3.2.21) lib/active_support/dependencies.rb:192:in `block in const_missing'
  activesupport (3.2.21) lib/active_support/dependencies.rb:190:in `const_missing'
  app/controllers/application_controller.rb:309:in `find_community'
  app/controllers/application_controller.rb:212:in `fetch_community'
  activesupport (3.2.21) lib/active_support/callbacks.rb:429:in `_run__957043731__process_action__735198160__callbacks'
  activesupport (3.2.21) lib/active_support/callbacks.rb:405:in `__run_callback'
  activesupport (3.2.21) lib/active_support/callbacks.rb:385:in `_run_process_action_callbacks'
  activesupport (3.2.21) lib/active_support/callbacks.rb:81:in `run_callbacks'
  actionpack (3.2.21) lib/abstract_controller/callbacks.rb:17:in `process_action'
  actionpack (3.2.21) lib/action_controller/metal/rescue.rb:29:in `process_action'
  actionpack (3.2.21) lib/action_controller/metal/instrumentation.rb:30:in `block in process_action'
  activesupport (3.2.21) lib/active_support/notifications.rb:123:in `block in instrument'
  activesupport (3.2.21) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
  activesupport (3.2.21) lib/active_support/notifications.rb:123:in `instrument'
  actionpack (3.2.21) lib/action_controller/metal/instrumentation.rb:29:in `process_action'
  actionpack (3.2.21) lib/action_controller/metal/params_wrapper.rb:207:in `process_action'
  activerecord (3.2.21) lib/active_record/railties/controller_runtime.rb:18:in `process_action'
  actionpack (3.2.21) lib/abstract_controller/base.rb:121:in `process'
  actionpack (3.2.21) lib/abstract_controller/rendering.rb:45:in `process'
  actionpack (3.2.21) lib/action_controller/metal.rb:203:in `dispatch'
  actionpack (3.2.21) lib/action_controller/metal/rack_delegation.rb:14:in `dispatch'
  actionpack (3.2.21) lib/action_controller/metal.rb:246:in `block in action'
  actionpack (3.2.21) lib/action_dispatch/routing/route_set.rb:73:in `dispatch'
  actionpack (3.2.21) lib/action_dispatch/routing/route_set.rb:36:in `call'
  journey (1.0.4) lib/journey/router.rb:68:in `block in call'
  journey (1.0.4) lib/journey/router.rb:56:in `call'
  actionpack (3.2.21) lib/action_dispatch/routing/route_set.rb:608:in `call'
  omniauth (1.2.2) lib/omniauth/strategy.rb:186:in `call!'
  omniauth (1.2.2) lib/omniauth/strategy.rb:164:in `call'
  meta_request (0.3.4) lib/meta_request/middlewares/app_request_handler.rb:13:in `call'
  meta_request (0.3.4) lib/meta_request/middlewares/meta_request_handler.rb:13:in `call'
  lib/rack_middleware/custom_domain_cookie.rb:20:in `call'
  warden (1.2.3) lib/warden/manager.rb:35:in `block in call'
  warden (1.2.3) lib/warden/manager.rb:34:in `call'
  actionpack (3.2.21) lib/action_dispatch/middleware/best_standards_support.rb:17:in `call'
  rack (1.4.7) lib/rack/etag.rb:23:in `call'
  rack (1.4.7) lib/rack/conditionalget.rb:25:in `call'
  actionpack (3.2.21) lib/action_dispatch/middleware/head.rb:14:in `call'
  actionpack (3.2.21) lib/action_dispatch/middleware/params_parser.rb:21:in `call'
  actionpack (3.2.21) lib/action_dispatch/middleware/flash.rb:242:in `call'
  rack (1.4.7) lib/rack/session/abstract/id.rb:210:in `context'
  rack (1.4.7) lib/rack/session/abstract/id.rb:205:in `call'
  actionpack (3.2.21) lib/action_dispatch/middleware/cookies.rb:341:in `call'
  activerecord (3.2.21) lib/active_record/query_cache.rb:64:in `call'
  activerecord (3.2.21) lib/active_record/connection_adapters/abstract/connection_pool.rb:479:in `call'
  actionpack (3.2.21) lib/action_dispatch/middleware/callbacks.rb:28:in `block in call'
  activesupport (3.2.21) lib/active_support/callbacks.rb:405:in `_run__351738300__call__664303991__callbacks'
  activesupport (3.2.21) lib/active_support/callbacks.rb:405:in `__run_callback'
  activesupport (3.2.21) lib/active_support/callbacks.rb:385:in `_run_call_callbacks'
  activesupport (3.2.21) lib/active_support/callbacks.rb:81:in `run_callbacks'
  actionpack (3.2.21) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
  actionpack (3.2.21) lib/action_dispatch/middleware/reloader.rb:65:in `call'
  actionpack (3.2.21) lib/action_dispatch/middleware/remote_ip.rb:31:in `call'
  airbrake (4.1.0) lib/airbrake/rails/middleware.rb:13:in `call'
  rack-contrib (1.4.0) lib/rack/contrib/response_headers.rb:17:in `call'
  meta_request (0.3.4) lib/meta_request/middlewares/headers.rb:16:in `call'
  better_errors (2.1.1) lib/better_errors/middleware.rb:84:in `protected_app_call'
  better_errors (2.1.1) lib/better_errors/middleware.rb:79:in `better_errors_call'
  better_errors (2.1.1) lib/better_errors/middleware.rb:57:in `call'
  actionpack (3.2.21) lib/action_dispatch/middleware/debug_exceptions.rb:16:in `call'
  actionpack (3.2.21) lib/action_dispatch/middleware/show_exceptions.rb:56:in `call'
  lograge (0.3.4) lib/lograge/rails_ext/rack/logger.rb:15:in `call_app'
  railties (3.2.21) lib/rails/rack/logger.rb:18:in `call'
  quiet_assets (1.1.0) lib/quiet_assets.rb:27:in `call_with_quiet_assets'
  actionpack (3.2.21) lib/action_dispatch/middleware/request_id.rb:22:in `call'
  rack (1.4.7) lib/rack/methodoverride.rb:21:in `call'
  rack (1.4.7) lib/rack/runtime.rb:17:in `call'
  rack (1.4.7) lib/rack/lock.rb:15:in `call'
  rack-livereload (0.3.16) lib/rack/livereload.rb:23:in `_call'
  rack-livereload (0.3.16) lib/rack/livereload.rb:14:in `call'
  actionpack (3.2.21) lib/action_dispatch/middleware/static.rb:83:in `call'
  airbrake (4.1.0) lib/airbrake/user_informer.rb:16:in `_call'
  airbrake (4.1.0) lib/airbrake/user_informer.rb:12:in `call'
  railties (3.2.21) lib/rails/engine.rb:484:in `call'
  railties (3.2.21) lib/rails/application.rb:231:in `call'
  railties (3.2.21) lib/rails/railtie/configurable.rb:30:in `method_missing'
  rack (1.4.7) lib/rack/deflater.rb:13:in `call'
  rack (1.4.7) lib/rack/content_length.rb:14:in `call'
  railties (3.2.21) lib/rails/rack/log_tailer.rb:17:in `call'
  rack (1.4.7) lib/rack/handler/webrick.rb:59:in `service'
  /home/nazrul/.rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/webrick/httpserver.rb:138:in `service'
  /home/nazrul/.rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/webrick/httpserver.rb:94:in `run'
  /home/nazrul/.rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/webrick/server.rb:295:in `block in start_thread'

**Comment by rap1ds** [comment] 2015-10-02 18:02
Hello!

Please provide some additional information about your environment and add exact steps how to reproduce the issue. You can use the [Issue Template](https://raw.githubusercontent.com/sharetribe/sharetribe/master/ISSUE_TEMPLATE.md)

**Comment by nazrulio** [comment] 2015-10-02 19:01
##### Sharetribe Version: b58f578a1ebb251160f9bf1ad17c2c1e8b48c913

##### Environment: Linux Ubuntu 14.04

##### Server mode: Development

##### Description: I have followed the https://github.com/sharetribe/sharetribe instruction to setup sharetribe in development mode. After installation i run the server and it's running. But when i browse the project localhost:3000 then it shows "undefined method `[]=' for nil:NilClass:
  delayed_paperclip (2.9.1) lib/delayed_paperclip.rb:52:in `process_in_background'".

##### Steps To Reproduce: Run application rails server RAILS_ENV=development and browse localhost:3000 

##### Expected Result: Should show "controller":"homepage","action":"index" page and run application successfully.

##### Actual Result:

##### Additional information

**Comment by nazrulio** [comment] 2015-10-03 04:55
I found another solution. All process_in_background must be declared after has_attached_file

  process_in_background :logo
  process_in_background :wide_logo
  process_in_background :cover_photo
  process_in_background :small_cover_photo
  process_in_background :favicon

**Comment by JahBrewski** [comment] 2015-10-03 14:40
Wow, thanks @nazrulio! I just had this same error.

**Comment by rap1ds** [comment] 2015-10-05 12:56
@nazrulio @JahBrewski Thanks for additional information!

I can see that your delayed_paperclip version is 2.9.1, which is not the same we have in Gemfile.lock 2.6.1. Why is that? Did you run `bundle update delayed_paperclip` or something like that?

**Comment by rap1ds** [comment] 2015-10-13 05:27
My guess is that the issue was due to incompatible delayed_paperclip version. I'm closing this issue, but if you have any additional information, feel free to post it to this thread.

**Closed by rap1ds** 2015-10-13 05:27 UTC
Labels: more information needed
