### ISSUE TITLE
Changing default currency

### ISSUE THREAD

**Issue by wjurkowlaniec** [sharetribe/sharetribe#2980] opened 2017-06-08 16:45 UTC
_Please add only one problem per Issue. If you are facing multiple problems, add multiple Issues._

##### Sharetribe Version:
ada54dd6508fb30c09dc58e1ecae474f9f1eb502

##### Environment:

Linux

##### Server mode:

Production mode

##### Description:

I don't know how to change the default USD currency to different one. I took following steps:

##### Steps To Reproduce:

1. Added own format in config/initializers/money.rb

config.default_currency = :uah

config.register_currency = {
    :priority            => 1,
    :iso_code            => "UAH",
    :name                => "Hryvnia",
    :symbol              => "UAH",
    :alternate_symbols   => ["Fr", "SFr"],
    :subunit             => "Kopiyka",
    :subunit_to_unit     => 100,
    :symbol_first        => true,
    :html_entity         => "&#8372;",
    :decimal_mark        => ".",
    :thousands_separator => ",",
    :iso_numeric         => "980"
  }

2. run migrations

RAILS_ENV=production bundle exec rake db:migrate

3. Restarted server 

Expected result: 

Change currency to ukrainian hryvnia in posting new item

Actual result: _What was the actual result after running the steps above?_

 $ sign in posting new item

**Comment by rap1ds** [comment] 2017-06-09 10:05
Hi, thanks for reporting the issue. Go to your database, open the `communities` table and edit the `currency` column. Change the value `USD` to `UAH`. That should do the trick.

I'm closing this issue because it seems that this is not a bug in Sharetribe code. Feel free to continue the discussion here or in the [community forum](https://www.sharetribe.com/community/)

**Closed by rap1ds** 2017-06-09 10:05 UTC
