### ISSUE TITLE
System memory keeps increasing until it fills up entire RAM

### ISSUE THREAD

**Issue by ankurj77** [sharetribe/sharetribe#1834] opened 2016-03-21 04:32 UTC
##### Sharetribe Version:
v5.6.0 => commit d1ea5a4e9bf2cabaa2e6af259969d0c29998c307

##### Environment:
Google Cloud Server - Ubuntu
Linux 3.19.0-56-generic #62~14.04.1-Ubuntu SMP x86_64 x86_64 x86_64 GNU/Linux

##### Server mode:
Development Mode

##### Description:
I run the server and delayed jobs worker in background using following commands:
nohup bundle exec rake jobs:work >> log/delayed-jobs-worker.log 2>&1 &
nohup bundle exec rails server -b 0.0.0.0 > log/web-server.log 2>&1 &

The RAM usage at the time of start is ~500MB of which 12% is taken by delayed jobs worker and 5% by rails web server. After a few hours of browsing, the delayed jobs worker memory usage increases and fills up the entire RAM rendering the instance unusable. I have to reset the instance and restart the servers.

##### Steps To Reproduce:
1. Start the development webserver and delayed jobs worker.
2. start htop to look at memory usage.

Expected result: Memory usage should not keep increasing on usage.
Actual result: Memory usage fills up the entire RAM of 5GB in 4-5 hours.

**Comment by mooreds** [comment] 2016-03-22 01:51
This might be the issue: https://github.com/collectiveidea/delayed_job/issues/776

**Comment by mooreds** [comment] 2016-03-22 02:19
Looks like it is "working as designed" in development mode: https://github.com/collectiveidea/delayed_job/issues/776#issuecomment-151174427

**Comment by rap1ds** [comment] 2016-03-22 06:56
Thanks @mooreds for digging up the link to the Delayed Job issue!

I'm closing this issue because it's not an issue with Sharetribe codebase.

Remember to run your app in `development` mode only when doing development on your local machine.

**Closed by rap1ds** 2016-03-22 06:56 UTC

**Comment by ankurj77** [comment] 2016-03-23 04:51
Thanks guys! Just the single config change fixed for me.
