### ISSUE TITLE
Expose External API

### ISSUE THREAD

**Issue by samuelreh** [sharetribe/sharetribe#1457] opened 2015-09-29 21:48 UTC
It looks like there are several markdown files documenting a JSON REST API throughout the project:

https://github.com/sharetribe/sharetribe/blob/master/app/services/paypal_service/accounts_api.md
https://github.com/sharetribe/sharetribe/blob/master/app/services/listing_service/category_api.md
https://github.com/sharetribe/sharetribe/blob/master/app/services/listing_service/listings_api.md
https://github.com/sharetribe/sharetribe/blob/master/app/services/transaction_service/transactions_api.md

However, I can't figure out where in the code base these are exposed. Can someone point me in the right direction?

**Comment by rap1ds** [comment] 2015-09-30 05:22
Hi @samuelreh! Thanks for asking!

The APIs are (currently) internal APIs and they are not exposed to public (yet).

We are on our way to do some bigger architectural changes. Little by little, we are planning to take pieces of the Rails code and run them on a separate service. At the same time we will also expose some of these APIs to public. So the current internal APIs are only preparation for this change.

Btw. have you seen the technical roadmap we wrote a week or two ago? https://github.com/sharetribe/sharetribe/blob/master/TECHNICAL_ROADMAP.md#an-api

I'm closing this issues since it's not a bug in the code, but feel free to continue discussion in this thread.

**Closed by rap1ds** 2015-09-30 05:22 UTC

**Comment by Edwin-iter** [comment] 2017-08-18 01:30
Hi Team,

I'm trying to expose the devise authentication in a api to login-out in another app. Something like an mobile app. So in this point we need to know if that services was building or we don't have the public API yet. 

Regards
