### ISSUE TITLE
stable branch

### ISSUE THREAD

**Issue by infiniteschema** [sharetribe/sharetribe#2063] opened 2016-05-21 05:12 UTC
Hello,

First off, thank you for this excellent project! I've noticed that master is being used as the main dev branch. I'd like to suggest (or request) a stable branch which would be merged at each new version. I think this would be one of the simpler minor workflow tweaks that would lead to greater adoption of Sharetribe, as opposed to all users always having to look up the latest stable commit and merge it at each update.

Thanks again!

**Comment by rap1ds** [comment] 2016-05-23 07:13
Thanks for the suggestion!

I'd say our `master` branch is a "stable" branch:

* We never merge any changes to master if they break something
* We always deploy master branch to production immediately after we have merged any changes to master. www.sharetribe.com is always running the latest master branch.

If you want something even more stable, you can of course follow the [releases](https://github.com/sharetribe/sharetribe/releases).

Btw. is this something that should be communicated in the README?

**Comment by rap1ds** [comment] 2016-05-23 07:14
I'm closing this issue because it's not a bug in the Sharetribe code, but feel free to continue discussion in this thread.

**Closed by rap1ds** 2016-05-23 07:14 UTC

**Comment by infiniteschema** [comment] 2016-05-23 07:29
Thanks for the additional info. Admittedly this project is new to me, but as I was checking it out a number of times over the past week or so, I noticed the travis-ci.org unit testing build badge on master said "failing". I assumed, perhaps incorrectly, that this implicitly meant the master code may not be stable at these points. Although I was not aware that the .com is always running the latest master branch.

Personally I think this would be helpful to be communicated in the README, but others' opinions may differ.

**Comment by rap1ds** [comment] 2016-05-23 08:39
Yeah, damn those randomly failing Cucumber tests 😟
