### ISSUE TITLE
Why doesn't support secured CloudFront.

### ISSUE THREAD

**Issue by llvc** [sharetribe/sharetribe#2197] opened 2016-06-30 04:59 UTC
I set the CDN in sharetribe. but the html page in sharetribe is configured normal CDN url. Our app supports https. so not secured CDN url is blocked. In fact AWS CloudFront supports the secured http. 
![screen shot 2016-06-29 at 8 39 48 pm](https://cloud.githubusercontent.com/assets/12979715/16477225/361d21a2-3e90-11e6-8e1c-2f8a6b68da31.png)

I need the quick help

**Comment by bladealslayer** [comment] 2016-07-05 14:23
Duplicate of #2178

**Closed by bladealslayer** 2016-07-05 14:23 UTC
