### ISSUE TITLE
Routes error - Rails 4 version

### ISSUE THREAD

**Issue by eltonokada** [sharetribe/sharetribe#1639] opened 2016-01-13 18:05 UTC
I've just installed a fresh copy of sharetribe, i've done this more than 10 times, and now with the Rails 4 version i am getting this message:

"Message from application: You should not use the `match` method in your router without specifying an HTTP method.
If you want to expose your action to both GET and POST, add `via: [:get, :post]` option.
If you want to expose your action to GET, use `get` in the router:
  Instead of: match "controller#action"
  Do: get "controller#action" (RuntimeError)"

Should be something with the Rails 4 update, i will now use an older version, thanks

**Comment by rap1ds** [comment] 2016-01-19 08:24
Hi @eltonokada Thanks for reporting the issue. Indeed, this looks like Rails 4 issue.

Can you give me exact steps how to reproduce the issue with a fresh installation?

**Comment by eltonokada** [comment] 2016-01-23 14:43
i've installed in Digital Ocean VPS Ubuntu

I've just follow the installation guide, clone the code install all the gems and etc
https://github.com/sharetribe/sharetribe#installation

**Comment by rap1ds** [comment] 2016-02-22 13:13
I'm not able to reproduce this with the newest version 5.4.0.

Do you still have the issue?

I'm closing this ticket, but if you have any additional information how to reproduce the bug that would be helpful!

**Closed by rap1ds** 2016-02-22 13:13 UTC
Labels: more information needed
