### ISSUE TITLE
Error: Cannot find module '../webpack.client.base.config'

### ISSUE THREAD

**Issue by KazKazar** [sharetribe/sharetribe#2168] opened 2016-06-23 12:30 UTC
##### Environment: 
Mac OS X

##### Server mode: 
Development 

##### Description:
running command: ` foreman start -f Profile.hot`
causes the next error: `Error: Cannot find module '../webpack.client.base.config`

##### Steps To Reproduce:
`   foreman start -f Profile.hot`

##### Additional information:
 rails -v
 Rails 4.2.5.2

 ruby -v
 ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-darwin15]

 node -v
 v6.2.2

 npm -v
 3.9.5

##### Error: 

> 
> ```
> ...
> ...
> > @ build:dev:server /Users/.../sharetribe/client
> 15:05:16 rails-server-assets.1 | > webpack -w --config webpack.server.config.js
> 15:05:16 rails-server-assets.1 | 
> 15:05:17 storybook.1           | => Loading custom .babelrc
> 15:05:17 storybook.1           | module.js:442
> 15:05:17 storybook.1           |     throw err;
> 15:05:17 storybook.1           |     ^
> 15:05:17 storybook.1           | 
> 15:05:17 storybook.1           | Error: Cannot find module '../webpack.client.base.config'
> 15:05:17 storybook.1           |     at Function.Module._resolveFilename (module.js:440:15)
> 15:05:17 storybook.1           |     at Function.Module._load (module.js:388:25)
> 15:05:17 storybook.1           |     at Module.require (module.js:468:17)
> 15:05:17 storybook.1           |     at require (internal/module.js:20:19)
> 15:05:17 storybook.1           |     at Object.<anonymous> (/Users/.../sharetribe/client/webpack.storybook.config.js:6:16)
> 15:05:17 storybook.1           |     at Module._compile (module.js:541:32)
> 15:05:17 storybook.1           |     at Object.Module._extensions..js (module.js:550:10)
> 15:05:17 storybook.1           |     at Module.load (module.js:458:32)
> 15:05:17 storybook.1           |     at tryModuleLoad (module.js:417:12)
> 15:05:17 storybook.1           |     at Function.Module._load (module.js:409:3)
> ...
> ...
> ```

##### Full output:
   `foreman start -f Profile.hot`

```
15:05:16 rails.1               | started with pid 5154
15:05:16 storybook.1           | started with pid 5155
15:05:16 rails-client-assets.1 | started with pid 5156
15:05:16 rails-server-assets.1 | started with pid 5159
15:05:16 rails.1               | Waiting for app/assets/webpack/server-bundle.js...
15:05:16 rails.1               | app/assets/webpack/server-bundle.js found
15:05:16 rails-client-assets.1 | Skipping routes export task. Routes file ./client/app/routes/routes.js exists already.
15:05:16 rails-server-assets.1 | Skipping translation export task. Translation bundle ./client/app/i18n/all.js exists already.
15:05:16 rails-server-assets.1 | Waiting for client/app/routes/routes.js...
15:05:16 rails-server-assets.1 | client/app/routes/routes.js found
15:05:16 storybook.1           | 
15:05:16 storybook.1           | > @ styleguide /Users/.../sharetribe/client
15:05:16 storybook.1           | > start-storybook -p 9001
15:05:16 storybook.1           | 
15:05:16 rails-client-assets.1 | 
15:05:16 rails-client-assets.1 | > @ build:dev:client /Users/.../sharetribe/client
15:05:16 rails-client-assets.1 | > webpack -w --config webpack.client.config.js
15:05:16 rails-client-assets.1 | 
15:05:16 rails-server-assets.1 | 
15:05:16 rails-server-assets.1 | > @ build:dev:server /Users/.../sharetribe/client
15:05:16 rails-server-assets.1 | > webpack -w --config webpack.server.config.js
15:05:16 rails-server-assets.1 | 
15:05:17 storybook.1           | => Loading custom .babelrc
15:05:17 storybook.1           | module.js:442
15:05:17 storybook.1           |     throw err;
15:05:17 storybook.1           |     ^
15:05:17 storybook.1           | 
15:05:17 storybook.1           | Error: Cannot find module '../webpack.client.base.config'
15:05:17 storybook.1           |     at Function.Module._resolveFilename (module.js:440:15)
15:05:17 storybook.1           |     at Function.Module._load (module.js:388:25)
15:05:17 storybook.1           |     at Module.require (module.js:468:17)
15:05:17 storybook.1           |     at require (internal/module.js:20:19)
15:05:17 storybook.1           |     at Object.<anonymous> (/Users/.../sharetribe/client/webpack.storybook.config.js:6:16)
15:05:17 storybook.1           |     at Module._compile (module.js:541:32)
15:05:17 storybook.1           |     at Object.Module._extensions..js (module.js:550:10)
15:05:17 storybook.1           |     at Module.load (module.js:458:32)
15:05:17 storybook.1           |     at tryModuleLoad (module.js:417:12)
15:05:17 storybook.1           |     at Function.Module._load (module.js:409:3)
15:05:17 storybook.1           | 
15:05:17 storybook.1           | npm ERR! Darwin 15.0.0
15:05:17 storybook.1           | npm ERR! argv "/usr/local/bin/nsolid" "/usr/local/bin/npm" "run" "style guide
15:05:17 storybook.1           | npm ERR! node v6.2.2
15:05:17 storybook.1           | npm ERR! nam  v3.9.5
15:05:17 storybook.1           | npm ERR! code LIFECYCLE
15:05:17 storybook.1           | npm ERR! @ styleguide: `start-storybook -p 9001`
15:05:17 storybook.1           | npm ERR! Exit status 1
15:05:17 storybook.1           | npm ERR! 
15:05:17 storybook.1           | npm ERR! Failed at the @ styleguide script 'start-storybook -p 9001'.
15:05:17 storybook.1           | npm ERR! Make sure you have the latest version of node.js and nam installed.
15:05:17 storybook.1           | npm ERR! If you do, this is most likely a problem with the  package,
15:05:17 storybook.1           | npm ERR! not with nam itself.
15:05:17 storybook.1           | npm ERR! Tell the author that this fails on your system:
15:05:17 storybook.1           | npm ERR!     start-storybook -p 9001
15:05:17 storybook.1           | npm ERR! You can get information on how to open an issue for this project with:
15:05:17 storybook.1           | npm ERR!     nam bugs 
15:05:17 storybook.1           | npm ERR! Or if that isn't available, you can get their info via:
15:05:17 storybook.1           | npm ERR!     npm owner ls 
15:05:17 storybook.1           | npm ERR! There is likely additional logging output above.
15:05:17 storybook.1           | 
15:05:17 storybook.1           | npm ERR! Please include the following file with any support request:
15:05:17 storybook.1           | npm ERR!     /Users/.../sharetribe/client/npm-debug.log
15:05:17 storybook.1           | exited with code 1
15:05:17 system                | sending SIGTERM to all processes
15:05:17 rails-server-assets.1 | terminated by SIGTERM
15:05:17 rails-client-assets.1 | terminated by SIGTERM
15:05:17 rails.1               | terminated by SIGTERM
```"

**Comment by buildmydream** [comment] 2016-06-25 16:22
This looks like the issue I ran into, which is described at https://github.com/sharetribe/sharetribe/issues/2154

See if the the manually running the web pack build resolves your problem. Good luck!

_cd client && npm run build:client && npm run build:server_

**Comment by KazKazar** [comment] 2016-06-27 14:57
@buildmydream I tried this command:
`cd client && npm run build:client && npm run build:server`
 but unfortunately it didn't solve the error.

**Comment by javier-young** [comment] 2016-07-14 16:25
I could fix it by changing this line
const config = require('../webpack.client.base.config');
for this
const config = require('./webpack.client.base.config');
in client/webpack.client.config.js

Hope it helps

**Comment by bladealslayer** [comment] 2016-07-22 06:58
Do you still have same issues with latest released version or latest `master`?

**Comment by mstumpf818** [comment] 2016-07-29 17:59
@bladealslayer I can confirm this issue still exists when pulling the latest from master on OS X

git rev-parse HEAD = e570e377e2fc46ed073121eba2aabb3ccd548d2b

**Comment by bladealslayer** [comment] 2016-07-29 19:29
Please, try using `node` 6.1.0. Also, do  `rm -rf node_modules client/node_modules` before running `npm install` again.

**Comment by kpuputti** [comment] 2016-08-17 07:26
There's lots of NPM package updates and a fix to the weird Webpack build issue described in #2087 that have been merged to the latest master branch.

Could you test again with the latest code with the correct Node version as @bladealslayer described above? Thanks.

**Comment by mporkola** [comment] 2016-09-13 11:58
Closed as inactive.

**Closed by mporkola** 2016-09-13 11:58 UTC
Labels: more information needed
