### ISSUE TITLE
Processing Uploaded Image

### ISSUE THREAD

**Issue by manishkongari** [sharetribe/sharetribe#1559] opened 2015-11-20 01:23 UTC
It is displaying "Processing Uploaded Image " for like ever
does not display image in development
am not using  
#gem 'asset_sync'
#gem 'aws-sdk-v1'
#gem 'aws-sdk', '~> 2'

commented in application.rb
   if (APP_CONFIG.s3_bucket_name && APP_CONFIG.aws_access_key_id && APP_CONFIG.aws_secret_access_key)
     paperclip_options.merge!({
       :path => "images/:class/:attachment/:id/:style/:filename",
       :url => ":s3_domain_url",
       :storage => :s3,
       :s3_protocol => 'https',
       :s3_credentials => {
             :bucket            => APP_CONFIG.s3_bucket_name,
             :access_key_id     => APP_CONFIG.aws_access_key_id,
             :secret_access_key => APP_CONFIG.aws_secret_access_key
       }
     })
   end

still no luck ,images does not display

**Comment by rap1ds** [comment] 2015-11-20 07:33
Do you have a worker process running? `rake jobs:work`

**Comment by manishkongari** [comment] 2015-11-20 15:10
Thanks rap1ds, it helped but how do i run `bundle exec rake RAILS_ENV=production jobs:work ` as daemon.

**Comment by manishkongari** [comment] 2015-11-20 15:46
paperclip works only when rake jobs:work is also made to run on other tab of terminal

**Comment by manishkongari** [comment] 2015-11-20 16:49
i resolved with this `RAILS_ENV=production bundle exec script/delayed_job start`

**Comment by manishkongari** [comment] 2015-11-20 16:52
I am running this on shared kernal VPS .i also have a shared web hosting with that daemonize is not allowed can i run share tribe on that server ?

**Comment by rap1ds** [comment] 2015-11-23 07:02
In order to run Sharetribe properly you have to be able to run at least 1 background job worker. We have some time consuming operations (e.g. image processing) that we definitely do not want to do during the HTTP request cycle, so that's why the background worker is required.

I'm closing this issue since it's not a bug in Sharetribe codebase.

**Closed by rap1ds** 2015-11-23 07:02 UTC

**Comment by indy-guide** [comment] 2016-02-02 02:37
I have the same issue, but don't know how to solve it. I use Amazon's AWS.

**Comment by indy-guide** [comment] 2016-02-02 02:37
@manishkongari can you help me? Thank you!
