### ISSUE TITLE
S3 images not loading with 5.12

### ISSUE THREAD

**Issue by thecrabnebula** [sharetribe/sharetribe#2603] opened 2016-10-02 15:06 UTC
##### Sharetribe Version:
5.12

##### Environment:
Heroku

##### Server mode:
development

##### Description:
Since updating to 5.12, images will not load from us-west-2. This has been added to the s3_region variable specified in the documentation.

No other changes have been made to the server.

**Comment by pcm211** [comment] 2016-10-02 15:44
change the bucket location to US East (N Virginia) or use Cloudfront .... to make it work ...
PS See naming conventions of AWS ... 

Hope that solves your issue

**Comment by rap1ds** [comment] 2016-10-02 18:04
What was the previous working version you were running before the update?

**Comment by thecrabnebula** [comment] 2016-10-02 18:55
The previous version was 5.11.

**Comment by thecrabnebula** [comment] 2016-10-02 18:59
@pcm211: The naming convention used for the variable is the same as that in the config.default.yml. 

In the first instance, us-east-1 was tried, without success. 

The solution should not be "use Cloudfront" for something that has worked the way it is for a long time.

**Comment by rap1ds** [comment] 2016-10-03 06:02
@thecrabnebula Thanks for reporting the previous version number.

"Use CloudFront" is not the solution here. We don't do changes that requires you to change your hosting infra between version updates without specifically mentioning it in the upgrade notes.

**Comment by rap1ds** [comment] 2016-10-03 06:02
@bladealslayer Any ideas?

**Comment by pcm211** [comment] 2016-10-03 09:15
@thecrabnebula .... I have faced this problem ... code is not the problem it works the same ...the problem is the naming convention CALL ...US East has the config which calls as ... XXX.amazonaws.com ... rest calls are a bit longer ...  moreover do check that your bucket name does not have a dot "." in it ... because it changes the complete naming gambit 

@rap1ds  ... I feel we should add another param in the config file .. for the region in which the bucket is made and ammend the aws calling accordingly to seamlessly integrate all region buckets easily

**Comment by bladealslayer** [comment] 2016-10-03 13:41
@thecrabnebula do you have separate `s3_upload_bucket_name`? If yes, is that bucket also in `us-west-2`?

It seems we have possible issue with S3 uploads when there is separate uploads bucket in region other than `us-east-1`. However, I didn't see any issue with displaying images from `us-west-2` when testing. @thecrabnebula are previously uploaded images working and just uploads failing or all images don't display? We generate image URLs in the form `bucket-name.s3.amazonaws.com`, which normally gets redirected to the correct region endpoint.

Ideally, we should add `:s3_host_name` to paperclip options, in order to avoid the redirect and should support other regions in the uploader.

**Comment by thecrabnebula** [comment] 2016-10-04 22:07
Thanks to everyone for your help.
There is a separate name for the s3_upload_bucket and that is also us-west-2. It appears to be working now, but I am unsure why. None of the images were loading with 5.12, but now at least some of them are. I'm still testing.

**Comment by bladealslayer** [comment] 2016-10-05 08:34
I correct mysql, S3 uploader works fine with non-us-east-1 buckets as well. So, all in all, it all should work fine in `us-west-2`. The extra redirect will be eliminated with #2605.

**Comment by bladealslayer** [comment] 2016-10-05 08:34
Closing this. @thecrabnebula comment here if you still have issues.

**Closed by bladealslayer** 2016-10-05 08:34 UTC
Labels: more information needed
