### ISSUE TITLE
undefined method `countries' for CountrySelect:Module

### ISSUE THREAD

**Issue by bipashant** [sharetribe/sharetribe#1547] opened 2015-11-16 05:14 UTC
Hi,
I'm setting up fresh copy of sharetribe in my local machines. everything works fine but got the following error. I've done `bundle install` and followed every step as in provided documentation here. 

NoMethodError - undefined method `countries' for CountrySelect:Module:
  app/utils/localization_utils.rb:7:in `country_code_valid?'
  app/utils/localization_utils.rb:15:in `valid_country_code'
  app/controllers/listings_controller.rb:164:in `show'
  actionpack (3.2.21) lib/action_controller/metal/implicit_render.rb:4:in `send_action'
  actionpack (3.2.21) lib/abstract_controller/base.rb:167:in `process_action'
  actionpack (3.2.21) lib/action_controller/metal/rendering.rb:10:in `process_action'
  actionpack (3.2.21) lib/abstract_controller/callbacks.rb:18:in `block in process_action'
  activesupport (3.2.21) lib/active_support/callbacks.rb:667:in `_run__2770361941481203979__process_action__2919240351843765303__callbacks'
  activesupport (3.2.21) lib/active_support/callbacks.rb:405:in `__run_callback'
  activesupport (3.2.21) lib/active_support/callbacks.rb:385:in `_run_process_action_callbacks'
  activesupport (3.2.21) lib/active_support/callbacks.rb:81:in `run_callbacks'
  actionpack (3.2.21) lib/abstract_controller/callbacks.rb:17:in `process_action'
  actionpack (3.2.21) lib/action_controller/metal/rescue.rb:29:in `process_action'
  actionpack (3.2.21) lib/action_controller/metal/instrumentation.rb:30:in `block in process_action'
  activesupport (3.2.21) lib/active_support/notifications.rb:123:in `block in instrument'
  activesupport (3.2.21) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
  activesupport (3.2.21) lib/active_support/notifications.rb:123:in `instrument'
  actionpack (3.2.21) lib/action_controller/metal/instrumentation.rb:29:in `process_action'
  actionpack (3.2.21) lib/action_controller/metal/params_wrapper.rb:207:in `process_action'
  activerecord (3.2.21) lib/active_record/railties/controller_runtime.rb:18:in `process_action'
  actionpack (3.2.21) lib/abstract_controller/base.rb:121:in `process'
  actionpack (3.2.21) lib/abstract_controller/rendering.rb:45:in `process'
  actionpack (3.2.21) lib/action_controller/metal.rb:203:in `dispatch'
  actionpack (3.2.21) lib/action_controller/metal/rack_delegation.rb:14:in `dispatch'
  actionpack (3.2.21) lib/action_controller/metal.rb:246:in `block in action'
  actionpack (3.2.21) lib/action_dispatch/routing/route_set.rb:73:in `dispatch'
  actionpack (3.2.21) lib/action_dispatch/routing/route_set.rb:36:in `call'
  journey (1.0.4) lib/journey/router.rb:68:in `block in call'
  journey (1.0.4) lib/journey/router.rb:56:in `call'
  actionpack (3.2.21) lib/action_dispatch/routing/route_set.rb:608:in `call'
  omniauth (1.2.2) lib/omniauth/strategy.rb:186:in `call!'
  omniauth (1.2.2) lib/omniauth/strategy.rb:164:in `call'
  meta_request (0.3.4) lib/meta_request/middlewares/app_request_handler.rb:13:in `call'
  meta_request (0.3.4) lib/meta_request/middlewares/meta_request_handler.rb:13:in `call'
  lib/rack_middleware/custom_domain_cookie.rb:20:in `call'
  warden (1.2.3) lib/warden/manager.rb:35:in `block in call'
  warden (1.2.3) lib/warden/manager.rb:34:in `call'
  actionpack (3.2.21) lib/action_dispatch/middleware/best_standards_support.rb:17:in `call'
  rack (1.4.7) lib/rack/etag.rb:23:in `call'
  rack (1.4.7) lib/rack/conditionalget.rb:25:in `call'
  actionpack (3.2.21) lib/action_dispatch/middleware/head.rb:14:in `call'
  actionpack (3.2.21) lib/action_dispatch/middleware/params_parser.rb:21:in `call'
  actionpack (3.2.21) lib/action_dispatch/middleware/flash.rb:242:in `call'
  rack (1.4.7) lib/rack/session/abstract/id.rb:210:in `context'
  rack (1.4.7) lib/rack/session/abstract/id.rb:205:in `call'
  actionpack (3.2.21) lib/action_dispatch/middleware/cookies.rb:341:in `call'
  activerecord (3.2.21) lib/active_record/query_cache.rb:64:in `call'
  activerecord (3.2.21) lib/active_record/connection_adapters/abstract/connection_pool.rb:479:in `call'
  actionpack (3.2.21) lib/action_dispatch/middleware/callbacks.rb:28:in `block in call'
  activesupport (3.2.21) lib/active_support/callbacks.rb:405:in `_run__1275795911164999285__call__4194937421889846220__callbacks'
  activesupport (3.2.21) lib/active_support/callbacks.rb:405:in `__run_callback'
  activesupport (3.2.21) lib/active_support/callbacks.rb:385:in `_run_call_callbacks'
  activesupport (3.2.21) lib/active_support/callbacks.rb:81:in `run_callbacks'
  actionpack (3.2.21) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
  actionpack (3.2.21) lib/action_dispatch/middleware/reloader.rb:65:in `call'
  actionpack (3.2.21) lib/action_dispatch/middleware/remote_ip.rb:31:in `call'
  airbrake (4.1.0) lib/airbrake/rails/middleware.rb:13:in `call'
  rack-contrib (1.4.0) lib/rack/contrib/response_headers.rb:17:in `call'
  meta_request (0.3.4) lib/meta_request/middlewares/headers.rb:16:in `call'
  better_errors (2.1.1) lib/better_errors/middleware.rb:84:in `protected_app_call'
  better_errors (2.1.1) lib/better_errors/middleware.rb:79:in `better_errors_call'
  better_errors (2.1.1) lib/better_errors/middleware.rb:57:in `call'
  actionpack (3.2.21) lib/action_dispatch/middleware/debug_exceptions.rb:16:in `call'
  actionpack (3.2.21) lib/action_dispatch/middleware/show_exceptions.rb:56:in `call'
  lograge (0.3.4) lib/lograge/rails_ext/rack/logger.rb:15:in `call_app'
  railties (3.2.21) lib/rails/rack/logger.rb:18:in `call'
  quiet_assets (1.1.0) lib/quiet_assets.rb:27:in `call_with_quiet_assets'
  actionpack (3.2.21) lib/action_dispatch/middleware/request_id.rb:22:in `call'
  rack (1.4.7) lib/rack/methodoverride.rb:21:in `call'
  rack (1.4.7) lib/rack/runtime.rb:17:in `call'
  rack (1.4.7) lib/rack/lock.rb:15:in `call'
  rack-livereload (0.3.16) lib/rack/livereload.rb:23:in `_call'
  rack-livereload (0.3.16) lib/rack/livereload.rb:14:in `call'
  actionpack (3.2.21) lib/action_dispatch/middleware/static.rb:83:in `call'
  airbrake (4.1.0) lib/airbrake/user_informer.rb:16:in `_call'
  airbrake (4.1.0) lib/airbrake/user_informer.rb:12:in `call'
  railties (3.2.21) lib/rails/engine.rb:484:in `call'
  railties (3.2.21) lib/rails/application.rb:231:in `call'
  railties (3.2.21) lib/rails/railtie/configurable.rb:30:in `method_missing'
  rack (1.4.7) lib/rack/deflater.rb:13:in `call'
  rack (1.4.7) lib/rack/content_length.rb:14:in `call'
  railties (3.2.21) lib/rails/rack/log_tailer.rb:17:in `call'
  rack (1.4.7) lib/rack/handler/webrick.rb:59:in `service'

I'm not sure is there anything any additional step I need to perform to fix it.I'm from Nepal.Is there any relationship between my country and Localization module.
Any suggestion will be appreciated. Thank you

**Comment by rap1ds** [comment] 2015-11-17 06:42
Hi @bipashant 

Thanks for reporting the issue!

What's your `country_select` gem version number in Gemfile.lock?

**Comment by bipashant** [comment] 2015-11-17 06:59
I've `country_select (2.5.1)` in my Gemfile.lock

**Comment by rap1ds** [comment] 2015-11-17 08:31
I'm not able to reproduce this. I had slightly older version of CountrySelect installed, but after updating to 2.5.1, I'm still unable to reproduce this.

Are you able to give me any additional information which would help me to reproduce the issue?

**Comment by bipashant** [comment] 2015-11-17 11:06
I'm choosing country name 'Nepal' while creating market place. After this when I tried to visit home page It throws above error.

This line is from *sharetribe/app/utils/localization_utils.rb*
Error occurred in 
```ruby
# Check if the country code (ISO 3166-1 alpha-2) is valid (i.e. sv_SE -> SE is the country code)
  def country_code_valid?(country_code)
    unless country_code.blank?
      CountrySelect.countries.select{|key, hash|
       return true if key.downcase == country_code.downcase
      }
    end
    return false
  end
```
So for hotfix I commented all the line within this function and directly return true as below.I know this is not the solution.I'm not sure is this cause any effect to other module of the system.

``` ruby
# Check if the country code (ISO 3166-1 alpha-2) is valid (i.e. sv_SE -> SE is the country code)
  def country_code_valid?(country_code)
    # unless country_code.blank?
    #   CountrySelect.countries.select{|key, hash|
    #     return true if key.downcase == country_code.downcase
    #   }
    # end
    # return false
    return true
  end
```

**Comment by rap1ds** [comment] 2015-11-23 07:31
I'm still unable to reproduce this issue. I created a new marketplace with Nepal as a country, created a new listings and everything worked fine. If you are able to give me a steps to reproduce the issue that would be great.

I'm closing this issue now because I don't know how to move this forward without being able to reproduce the issue. Feel free to post here any additional information.

**Closed by rap1ds** 2015-11-23 07:31 UTC
Labels: more information needed

**Comment by eltonokada** [comment] 2016-01-11 17:18
I am having the same problem here,

My marketplace is Taiwan as a country... same error.

**Comment by eltonokada** [comment] 2016-01-11 17:19
I tried with versions of country_select gem, 2.5.1 and 1.2.0
