### ISSUE TITLE
Uservoice password reset doesn't work

### ISSUE THREAD

**Issue by mooreds** [sharetribe/sharetribe#2003] opened 2016-05-02 22:23 UTC
I'm trying to sign in to uservoice, but whenever I do I'm told my password is incorrect.

I then 'reset' my password.  When I go to the link sent to my email, I get this error message whatever I put in the new password fields:

```
Trusted client or admin required: Signature verification failed
```

Have tried with MS edge and chrome.

**Comment by rap1ds** [comment] 2016-05-03 07:35
Thanks for reporting!

I tried this myself (Chrome) but couldn't reproduce it. I successfully received the password reset email and clicking the link too me to a page that asked me to give a new password. Everything worked.

Can you try it once again? Just to make sure this wasn't something temporary. If the problem still persist, I will contact UserVoice.

I'm closing this issue, since it's not an open issue in Sharetribe's code, but feel free to continue discussion in this thread.

**Closed by rap1ds** 2016-05-03 07:35 UTC

**Comment by mooreds** [comment] 2016-05-03 14:11
Ah, must have been user error, as I was able to make it work fine today.  Thanks for the response!
