### ISSUE TITLE
How to configure AWS SES/SNS for e-mail?

### ISSUE THREAD

**Issue by dwidoo** [sharetribe/sharetribe#2195] opened 2016-06-29 17:14 UTC
##### Environment:

DigitalOcean

##### Server mode:

In production mode

##### Description:

When trying to set email outgoing addresse, I got the following:

```
Sender address: not set (using default address kidwi@kidwi.mom)
Status: An error occurred. Please refresh the page.
``` 

When trying to send e-mail test, I get the following error message `Marketplace temporarily unavailable`.

Should I use smtp settings for using SES / SNS or is there a better way? How did you configure e-mails on the hosted version please?

Thanks guys

**Comment by rap1ds** [comment] 2016-07-07 07:47
Hi @dwidoo 

Have a look at @gnomet 's answer in the Community Forum: https://www.sharetribe.com/community/t/how-to-configure-sharetribe-for-amazon-ses/179/3 I hope it helps!

If not, feel free to continue the discussion in the Community Forum.

I'm closing now this issue, since I think this is not a bug in the Sharetribe code, but instead a configuration issue.

**Closed by rap1ds** 2016-07-07 07:47 UTC
