### ISSUE TITLE
Feature request: Add a message to buyer with no stripe setup

### ISSUE THREAD

**Issue by geopast** [sharetribe/sharetribe#3221] opened 2018-01-24 02:05 UTC
_Please add only one problem per Issue. If you are facing multiple problems, add multiple Issues._

##### Sharetribe Version: 682dfa0733bb64e83cfd7893256c150092bc2109

_Share the git commit hash of the version of Sharetribe that you are using. You can find it by running `git rev-parse HEAD` in your Sharetribe directory._

##### Environment: 

_What's your environment? Mac OS X, Heroku, or something else?_

Ubuntu 16.04 on Google Cloud

_What's your node version? Run the following commands and copy the result here:_

```
> node v7.8.0
> npm v4.2.0
```

##### Server mode:

_Are you running in development or production mode?_ Production

##### Description:

_In our own words, briefly describe the issue. Please add enough details, yet be concise._

When a buyer tries first purchase, if they have no stripe setup, they see empty payment section. Would be good to have a message here and link to their payment setup.

##### Steps To Reproduce:

_List the actions that will reproduce the issue._

_This is the **most important** part of the issue report. If we're not able to reproduce the issue, there's not much we can do about it. Please provide precise steps how to reproduce the issue._

1. New buyer registers and clicks buy on item in marketplace
2. Buy form appears but missing payment section as they are not setup in Stripe

Expected result: _What was the expected result after running the steps above?_

A message explaining to buyer that they need to setup Stripe first.

Actual result: _What was the actual result after running the steps above?_

Blank payment section. All other sections are visible.

##### Additional information

_Please provide any additional information that helps debugging, e.g. log output or stack trace of the error_

**Comment by thomasmalbaux** [comment] 2018-01-24 19:36
Thanks for reporting.

I'm not sure to understand exactly though. Can you tell us a bit more or, even better, share a few screenshots that describe all the steps to reproduce this?

Buyer don't have to configure anything, only sellers must add their bank account number in their user settings.
If buyer don't see any option to pay, it's probably because the listing isn't configured (Order Types) to use online payments or, for some reasons, the credit card field provided by Stripe doesn't load (https, resource blocked, etc).

Let us know!

**Comment by geopast** [comment] 2018-02-21 21:59
Hi Thomas,
The idea here is a visual cue for sellers when they create their first listing. As you say, if the seller has no stripe setup then buyer will not see option to pay. I'm thinking a message should be sent to sellers when they create first listing to remind them to setup payment if they want to receive payment.

**Comment by thomasmalbaux** [comment] 2018-02-22 18:31
Thanks for the details!

Indeed, after a provider posts a new listing, a "sticky" info message will be visible all the time when they browse the marketplace. They can't close it and it will disappear only after they've connected their payment details. They also receive an email notification "Remember to add your payment details to receive payments" with a link to their payment settings.

There could be a few more notifications though, and we'll keep that suggestion in mind. Thanks for the input!

**Closed by thomasmalbaux** 2018-02-22 18:31 UTC
Labels: more information needed
