### ISSUE TITLE
Uploaded files not being displaying

### ISSUE THREAD

**Issue by ewallteam** [sharetribe/sharetribe#1936] opened 2016-04-21 10:30 UTC
Hi,

I have installed the sharetribe application on digitalocean server and the application is running correctly but the images uploaded are not displayed in frontend. Always shows "missing.png". Can you guys help me to resolve the issue.

**Comment by rap1ds** [comment] 2016-04-21 10:36
Hi! Thanks for reporting the issue.

Can you please use the issue template, or at least answer to all questions in the template, such as your Sharetribe version and steps to reproduce. We can help you and fix the issue if we are able to reproduce the issue and for that we need the steps how to do it.

If you think this is not a bug in the code and instead you are looking for installation support, please visit the community forum https://www.sharetribe.com/community

**Comment by ewallteam** [comment] 2016-04-21 10:53
Thanks @rap1ds 

I am not sure it is bug or not. I have followed your installation instruction and install the same. I have just going to admin users profile and upload the avatar images. But it always shows "http://ewallsolutions.org/images/thumb/missing.png" .

**Comment by rap1ds** [comment] 2016-05-09 06:05
I'm closing this issue because it doesn't sound like an issue in Sharetribe codebase. You might want to ask help from the community forum https://www.sharetribe.com/community There may be people who have installed Sharetribe on Digital Ocean.

**Closed by rap1ds** 2016-05-09 06:05 UTC
Labels: more information needed
