### ISSUE TITLE
Customizing the app code

### ISSUE THREAD

**Issue by nchatu** [sharetribe/sharetribe#1495] opened 2015-10-14 19:54 UTC
I am opening this issue to know how to extend the Sharetribe app code without changing the source files. I know there is an option in admin area to change the template using css/js but I want to modify the Sharetribe source codes in order to add extra functionality. I can do this by editing the ST codes directly but want to preserve the change done when upgrade to a greater version.

Looking at the app code I don't see an extension mechanism. (like Spree). Is there any good approach I can use here?

**Comment by rap1ds** [comment] 2015-10-20 04:54
Hi @nchatu Thanks for asking!

Currently we don't have an easy way to add your own extension. However, we are painfully aware that this kind of plugin system is much needed by many people. We have done some planning how this could be done in the future, but nothing has yet happened.

I'm closing this issue, since it's not a bug in the Sharetribe code. However, feel free to continue discussion in this thread.

**Closed by rap1ds** 2015-10-20 04:54 UTC
