### ISSUE TITLE
Is there an option to know the number of times a listing was seen?

### ISSUE THREAD

**Issue by jolly17** [sharetribe/sharetribe#2860] opened 2017-02-02 04:10 UTC
I noticed a column in "listings" table saying "times_viewed" but the value is 0 for all my listings. Is there any way I can get the counter set for number of times a listing is visited, so that I can sort by popularity or show it on the listing itself etc..? Am I missing something here?

**Comment by rap1ds** [comment] 2017-02-02 06:45
Hi @jolly17 and thanks for asking.

See this reply in the community forum. It should answer to your question: https://www.sharetribe.com/community/t/statistics-for-sellers-vendors/406/2?u=rap1ds

I'm closing this issue now because it's not a bug in the Sharetribe code, but feel free to continue the discussion in this thread or in the Community forum thread.

**Closed by rap1ds** 2017-02-02 06:45 UTC
