### ISSUE TITLE
Webpack hangs after first run with foreman start -f Procfile.static

### ISSUE THREAD

**Issue by mstumpf818** [sharetribe/sharetribe#2343] opened 2016-07-29 19:51 UTC
##### Sharetribe Version:

git rev-parse HEAD = 66dc388f9c11c8c2cfc26b0ffe7567b1f5166655
##### Environment:

Mac OS X  10.11.6
##### Server mode:

development
##### Description:

After cloning from the master branch, the instructions [here](https://github.com/sharetribe/sharetribe/blob/master/README.md) for setting up a dev environment work and I can see http://lvh.me:3000.  After stopping foreman and running foreman start -f Procfile.static again, the webpack command hangs and never finishes.

I've deleted the node modules folder and reinstalled to no avail.

My previous clone was of the master branch a week ago and this didn't occur but after updating to the latest master branch today I cannot get it to work.
##### Steps To Reproduce:
1. Set up dev environment according to: https://github.com/sharetribe/sharetribe/blob/master/README.md
2. Start the dev server with foreman start -f Procfile.static
3. Quit foreman using ctrl+'c'
4. Run foreman again with foreman start -f Procfile.static

Expected result: The dev server can be stopped and started as many times as needed

Actual result: The dev server does not start because the webpack command hangs
##### Additional information

$ foreman start -f Procfile.static
15:49:54 rails.1               | started with pid 23653
15:49:54 rails-client-assets.1 | started with pid 23654
15:49:54 rails-server-assets.1 | started with pid 23655
15:49:54 rails.1               | Waiting for app/assets/webpack/server-bundle.js...
15:49:54 rails.1               | app/assets/webpack/server-bundle.js found
15:49:54 rails-client-assets.1 | Skipping routes export task. Routes file ./client/app/routes/routes.js exists already.
15:49:54 rails-server-assets.1 | Skipping translation export task. Translation bundle ./client/app/i18n/all.js exists already.
15:49:54 rails-server-assets.1 | Waiting for client/app/routes/routes.js...
15:49:54 rails-server-assets.1 | client/app/routes/routes.js found
15:49:55 rails-client-assets.1 | 
15:49:55 rails-client-assets.1 | > @ build:dev:client /Users/mstumpf/Work/dev.eivey.com/client
15:49:55 rails-client-assets.1 | > webpack -w --config webpack.client.config.js
15:49:55 rails-client-assets.1 | 
15:49:55 rails-server-assets.1 | 
15:49:55 rails-server-assets.1 | > @ build:dev:server /Users/mstumpf/Work/dev.eivey.com/client
15:49:55 rails-server-assets.1 | > webpack -w --config webpack.server.config.js
15:49:55 rails-server-assets.1 | 
15:49:55 rails-client-assets.1 | Webpack dev build for Rails
15:50:00 rails.1               | [2016-07-29 15:50:00] INFO  WEBrick 1.3.1
15:50:00 rails.1               | [2016-07-29 15:50:00] INFO  ruby 2.3.1 (2016-04-26) [x86_64-darwin15]
15:50:00 rails.1               | [2016-07-29 15:50:00] INFO  WEBrick::HTTPServer#start: pid=23659 port=3000
15:50:01 rails-server-assets.1 | Hash: 03b5b9eb2f400e7033f8
15:50:01 rails-server-assets.1 | Version: webpack 1.13.1
15:50:01 rails-server-assets.1 | Time: 5426ms
15:50:01 rails-server-assets.1 |            Asset     Size  Chunks             Chunk Names
15:50:01 rails-server-assets.1 | server-bundle.js  2.29 MB       0  [emitted]  main
15:50:01 rails-server-assets.1 |    [0] multi main 40 bytes {0} [built]
15:50:01 rails-server-assets.1 |  [598] ./app/i18n/all.js 290 kB {0} [optional] [built]
15:50:01 rails-server-assets.1 |  [601] ./app/routes/routes.js 146 kB {0} [optional] [built]
15:50:01 rails-server-assets.1 |     + 675 hidden modules
15:50:02 rails-client-assets.1 | Hash: 769a47bae9de3a032ca5
15:50:02 rails-client-assets.1 | Version: webpack 1.13.1
15:50:02 rails-client-assets.1 | Time: 6766ms
15:50:02 rails-client-assets.1 |            Asset     Size  Chunks             Chunk Names
15:50:02 rails-client-assets.1 |    app-bundle.js  4.68 MB       0  [emitted]  app
15:50:02 rails-client-assets.1 | vendor-bundle.js   312 kB       1  [emitted]  vendor
15:50:02 rails-client-assets.1 |   app-bundle.css  45.5 kB       0  [emitted]  app
15:50:02 rails-client-assets.1 |    [0] multi app 28 bytes {0} [built]
15:50:02 rails-client-assets.1 |    [0] multi vendor 52 bytes {1} [built]
15:50:02 rails-client-assets.1 |  [288] ./app/routes/routes.js 146 kB {0} [optional] [built]
15:50:02 rails-client-assets.1 |     + 384 hidden modules
15:50:02 rails-client-assets.1 | Child extract-text-webpack-plugin:
15:50:02 rails-client-assets.1 |         + 2 hidden modules
15:50:02 rails-client-assets.1 | Child extract-text-webpack-plugin:
15:50:02 rails-client-assets.1 |         + 2 hidden modules
15:50:02 rails-client-assets.1 | Child extract-text-webpack-plugin:
15:50:02 rails-client-assets.1 |         + 2 hidden modules
15:50:02 rails-client-assets.1 | Child extract-text-webpack-plugin:
15:50:02 rails-client-assets.1 |         + 2 hidden modules
15:50:02 rails-client-assets.1 | Child extract-text-webpack-plugin:
15:50:02 rails-client-assets.1 |         + 2 hidden modules
15:50:02 rails-client-assets.1 | Child extract-text-webpack-plugin:
15:50:02 rails-client-assets.1 |         + 2 hidden modules
15:50:02 rails-client-assets.1 | Child extract-text-webpack-plugin:
15:50:02 rails-client-assets.1 |         + 2 hidden modules
15:50:02 rails-client-assets.1 | Child extract-text-webpack-plugin:
15:50:02 rails-client-assets.1 |         + 2 hidden modules
15:50:02 rails-client-assets.1 | Child extract-text-webpack-plugin:
15:50:02 rails-client-assets.1 |         + 2 hidden modules
15:50:02 rails-client-assets.1 | Child extract-text-webpack-plugin:
15:50:02 rails-client-assets.1 |         + 2 hidden modules
15:50:02 rails-client-assets.1 | Child extract-text-webpack-plugin:
15:50:02 rails-client-assets.1 |         + 2 hidden modules
15:50:02 rails-client-assets.1 | Child extract-text-webpack-plugin:
15:50:02 rails-client-assets.1 |         + 2 hidden modules
15:50:02 rails-client-assets.1 | Child extract-text-webpack-plugin:
15:50:02 rails-client-assets.1 |         + 2 hidden modules
15:50:02 rails-client-assets.1 | Child extract-text-webpack-plugin:
15:50:02 rails-client-assets.1 |         + 2 hidden modules
15:50:02 rails-client-assets.1 | Child extract-text-webpack-plugin:
15:50:02 rails-client-assets.1 |         + 4 hidden modules
15:50:02 rails-client-assets.1 | Child extract-text-webpack-plugin:
15:50:02 rails-client-assets.1 |         + 2 hidden modules

**Comment by mstumpf818** [comment] 2016-08-01 14:39
i found that if you delete the app/assets/webpack before you run the command, it will then complete.  i'm not sure why this is though

**Comment by mstumpf818** [comment] 2016-08-01 15:09
it works if you modify the lines in Procfile.client-static and Procfile.static to 

rails-client-assets: rm -rf app/assets/webpack && script/export_routes_js.sh && cd client && npm run build:dev:client

**Comment by bladealslayer** [comment] 2016-08-03 12:09
@mstumpf818 thanks for reporting this. I think the intended way of doing this is to run `npm run clean` in between, but perhaps the procfile should indeed include that.

**Comment by Gnito** [comment] 2016-08-03 12:52
I can't reproduce this one. 

```
sharetribe gnito$ foreman start -f Procfile.static
15:41:32 rails.1               | started with pid 34242
15:41:32 rails-client-assets.1 | started with pid 34243
15:41:32 rails-server-assets.1 | started with pid 34244
...etc.
^CSIGINT received
15:44:37 system                | sending SIGTERM to all processes
15:44:37 rails-server-assets.1 | terminated by SIGTERM
15:44:37 rails-client-assets.1 | terminated by SIGTERM
15:44:37 rails.1               | terminated by SIGTERM
Vesas-MBP:sharetribe gnito$ foreman start -f Procfile.static
15:45:06 rails.1               | started with pid 34314
15:45:06 rails-client-assets.1 | started with pid 34315
15:45:06 rails-server-assets.1 | started with pid 34316
...etc.
```

**Comment by mstumpf818** [comment] 2016-08-03 19:58
@bladealslayer there is a "clean" command in package.json but i didn't see it being executed with foreman

**Comment by mstumpf818** [comment] 2016-08-03 20:02
@bladealslayer interestingly enough, when i change the procfile to use "npm run clean" instead of "rm -rf app/assets/webpack", it doesn't actually remove the webpack folder and so the command hangs again

**Comment by kpuputti** [comment] 2016-08-17 07:12
What do you mean with "the Webpack command hangs"? Which command?

The `npm run build:dev:client` and `npm run build:dev:server` commands that run the Webpack builds in `Procfile.static` and `Procfile.client-static` have watchers in them, so they are supposed to be left running and waiting for files to change.

If there was some other error, issue #2087 was fixed in master recently at that seems to have caused lots of weird errors in the Webpack builds. So you might want to try again with the latest master.

**Comment by mstumpf818** [comment] 2016-08-17 15:31
@kpuputti it "hangs" with the same output as the first post as it gets stuck trying to delete the webpack folder

**Comment by prmcewen** [comment] 2016-09-12 20:31
I am encountering the same issue

**Comment by lyyder** [comment] 2016-12-07 10:49
@mstumpf818 have you been able to get forward with this? From the log it looks like that the process is waiting for changes. Does the log output respond if you make changes in the client folder?

**Comment by rap1ds** [comment] 2016-12-15 06:58
Inactive. Closing.

**Closed** 2016-12-15 06:58 UTC
Labels: more information needed
