### ISSUE TITLE
Payment Gateway on Open Source Version

### ISSUE THREAD

**Issue by leofreitasusa** [sharetribe/sharetribe#2767] opened 2016-11-27 00:14 UTC
Hi,
I am new here i a really would appreciate your help.
I would like to install Sharetribe for my marketplace but i am really confused about method of payment.

1. Witch option do i have to integrate in my website?
2. How difficult would be to integrate it? From 0 to 10 for a specialized person in Ruby, what would be?
3. Is braintree or Strip the easiest solution?

Is there any programer interesting in install and make the integration?

Thank you,

**Comment by rap1ds** [comment] 2016-12-08 10:50
Hi @leofreitasusa 

This question has been asked and answered number of times here in Github Issues and in the Community forum, so instead of repeating my self, I'll just post links to point you to the previous answers:

https://github.com/sharetribe/sharetribe#payments
#2616 (Damn! I haven't yet answered!)
#1462
#1395
#1324
#1155
https://www.sharetribe.com/community/t/paypal-open-source-integration/288
https://www.sharetribe.com/community/t/paypal-payment-open-source/131/5
I've heard that some people have made their own PayPal implementation, so if you want to ask from them, I'd kindly direct you to the Community Forum. We try to keep Github Issues mainly for open issues in the code (bugs).

I'm closing this issue since this is not a bug in the Sharetribe code.

**Closed by rap1ds** 2016-12-08 10:50 UTC

**Comment by ramesh2007** [comment] 2017-11-21 05:39
@rap1ds 

I Thanks for your awesome support, I have question regarding payment gateways

what payment gateways will support for ST and below local turkey payment gateway will support sharetribe or not

https://www.iyzico.com/international

Thanks

**Comment by thomasmalbaux** [comment] 2017-11-21 06:37
Hi there Ramesh!

Right now both PayPal and Stripe are available as payment gateways. However it is true that not any of them supports Turkey right now.

We may add more gateways in the future but this isn't scheduled yet. If you're interested to build a custom integration with another payment provider, you could clone Sharetribe's code and develop the integration independently from us, or hire your own team to do it.

You can also discuss this with other open-source users in Sharetribe's Community forum at https://www.sharetribe.com/community/

Hopefully this helps!

**Comment by ramesh2007** [comment] 2017-11-21 06:47
Great thanks @thomasmalbaux

**Comment by shariff6** [comment] 2017-12-04 10:09
Hello @rap1ds does stripe work at production level, if so how do I enable it
