### ISSUE TITLE
Braintree Integration issue

### ISSUE THREAD

**Issue by shoaibmalik786** [sharetribe/sharetribe#1598] opened 2015-12-13 07:40 UTC
I need a help
i am trying to integrate braintree in my marketplace
but buyers are not able to see buy button, instead they can see request button and two datetime fields
and when they click on request they are redirected to the the transaction message page
no payment option is available.
please help what do i need to do?

Thanks

**Comment by ghost6p** [comment] 2015-12-15 01:33
I have the same issue.

Thanks in advance to whoever knows the solution.

**Comment by shoaibmalik786** [comment] 2015-12-16 17:11
Any response???

**Comment by rap1ds** [comment] 2015-12-17 07:15
Thanks for your question!

I'd have a look at the `transaction_processes` table. Make sure that the `listing_share` (a.k.a order type) is using a TransactionProcess that has a value `preauthorize` instead of `none`.

I hope that helps! 

A word of warning about Braintree support: Braintree support is something that will be probably removed at some point (or reimplemented), but I'm pretty sure it will not be there in the current form forever. We are not providing Braintree for our hosted version customers and we are mainly concentrating on PayPal support at the moment.

**Comment by rap1ds** [comment] 2015-12-17 07:34
I'm closing this issue now, because the core team is currently not concentrating on Braintree. If there's an issue in the code and you are able to fix it, we'll happy to review a Pull Request!

Feel free to continue the discussion in this thread even though the issue is closed.

**Closed by rap1ds** 2015-12-17 07:34 UTC
