### ISSUE TITLE
Add seller transaction fee

### ISSUE THREAD

**Issue by sunny2601** [sharetribe/sharetribe#1587] opened 2015-12-06 18:41 UTC
Hi all,
I want to add a functionality in my sytem where a seller and a buyer of a product registered with a mrketplace should pay commision (transaction fee) to the system admin 
Please suggest an aaproach to achive this functionality on sharetribe

Thanks And Regrads
Shakti

**Comment by rap1ds** [comment] 2015-12-08 07:49
Hi @sunny2601 !

Sounds somewhat difficult task to do! From the top of my head I can not give you a very comprehensive answer. Giving such answer would require significant design work and investigations. 

PaypalService is responsible for making the commission payment. In addition to that, you should probably change the way how TransactionService works. So have a look at those modules, maybe they'll lead you to the right track.

I'm closing this issue since it's not a bug in the Sharetribe code.

**Closed by rap1ds** 2015-12-08 07:49 UTC
