### ISSUE TITLE
Bundle install not successful?? #include <openssl/ssl.h> errors

### ISSUE THREAD

**Issue by chingjubb** [sharetribe/sharetribe#1597] opened 2015-12-12 07:05 UTC
Hi, I don't know where to ask the question regarding installation, so here it is:

I'm using Macbook pro 13" latest Yosemite, here's the when bundle install:
Please help, thanks!

Building native extensions.  This could take a while...
ERROR:  Error installing eventmachine:
	ERROR: Failed to build gem native extension.

    /Users/bb/.rvm/rubies/ruby-2.1.2/bin/ruby extconf.rb
checking for rb_trap_immediate in ruby.h,rubysig.h... no
checking for rb_thread_blocking_region()... yes
checking for inotify_init() in sys/inotify.h... no
checking for __NR_inotify_init in sys/syscall.h... no
checking for writev() in sys/uio.h... yes
checking for rb_wait_for_single_fd()... yes
checking for rb_enable_interrupt()... no
checking for rb_time_new()... yes
checking for sys/event.h... yes
checking for sys/queue.h... yes
creating Makefile

make "DESTDIR=" clean

make "DESTDIR="
compiling binder.cpp
In file included from binder.cpp:20:
./project.h:107:10: fatal error: 'openssl/ssl.h' file not found
#include <openssl/ssl.h>
         ^
1 error generated.
make: *** [binder.o] Error 1

make failed, exit code 2

**Comment by rap1ds** [comment] 2015-12-14 09:59
Hi @chingjubb ! Thanks for asking.

To be honest, I have no idea why this happens. We haven't seen or heard about this before.

Can you run `bundle install` in any other project?

I strongly suspect that this is not a bug in Sharetribe codebase, instead this is probably something related to your environment. That's why I'm closing the issue, but feel free to continue the discussion on this thread.

**Closed by rap1ds** 2015-12-14 09:59 UTC

**Comment by chingjubb** [comment] 2015-12-14 16:21
I can build my other projects in Rails,
only this one, I can’t build both on my Mac OS X and Windows 7,

 is it really the only time that you know about this issues??

and weird why does Ruby code has anything to do with #include <openssl/ssh.h> that’s C?

**Comment by rap1ds** [comment] 2015-12-14 16:27
What's the gem that fails to install? What are the lines before `Building native extensions. This could take a while...` ?

**Comment by snobeaver** [comment] 2015-12-16 16:16
I've also just attempted a 'bundle install' and am having the same issue. My other rails projects, on v4.x, all bundle install okay.

I get the following from bundle install:
- An error occurred while installing eventmachine (1.0.3), and Bundler cannot continue.
- Make sure that `gem install eventmachine -v '1.0.3'` succeeds before bundling.

I then attempt to install the gem and get the following:

Building native extensions.  This could take a while...
ERROR:  Error installing eventmachine:
	ERROR: Failed to build gem native extension.

    /Users/paulbarnes/.rvm/rubies/ruby-2.1.2/bin/ruby extconf.rb
checking for rb_trap_immediate in ruby.h,rubysig.h... no
checking for rb_thread_blocking_region()... yes
checking for inotify_init() in sys/inotify.h... no
checking for __NR_inotify_init in sys/syscall.h... no
checking for writev() in sys/uio.h... yes
checking for rb_wait_for_single_fd()... yes
checking for rb_enable_interrupt()... no
checking for rb_time_new()... yes
checking for sys/event.h... yes
checking for sys/queue.h... yes
creating Makefile

make "DESTDIR=" clean

make "DESTDIR="
compiling binder.cpp
In file included from binder.cpp:20:
./project.h:107:10: fatal error: 'openssl/ssl.h' file not found
#include <openssl/ssl.h>
         ^
1 error generated.
make: *** [binder.o] Error 1

make failed, exit code 2

Gem files will remain installed in /Users/paulbarnes/.rvm/gems/ruby-2.1.2/gems/eventmachine-1.0.3 for inspection.
Results logged to /Users/paulbarnes/.rvm/gems/ruby-2.1.2/extensions/x86_64-darwin-13/2.1.0-static/eventmachine-1.0.3/gem_make.out

----
FIX
-----
I fixed with the help of this issue post : https://github.com/eventmachine/eventmachine/issues/602
by running 'gem install eventmachine -v '1.0.3' -- --with-cppflags=-I/usr/local/opt/openssl/include' and then repeating 'bundle install'.

Hope that helps - seems to be an OpenSSL and Mac OSX El Capitan issue.

**Comment by rap1ds** [comment] 2015-12-17 07:32
Nice! Thanks @snobeaver for posting the fix!

@chingjubb can you try the fix and if it works, close the issue?
