### ISSUE TITLE
How can I enable paypal with sharetribe open source (latest) version?

### ISSUE THREAD

**Issue by vatex** [sharetribe/sharetribe#2792] opened 2016-12-07 23:10 UTC
How can I enable paypal with sharetribe open source (latest) version?
I already installed on AWS and now I need to enable paypal for payments and is it working on open source version?

**Comment by rap1ds** [comment] 2016-12-08 07:27
Hi @vatex !

This question has been asked and answered number of times here in Github Issues and in the Community forum, so instead of repeating my self, I'll just post links to point you to the previous answers:

* https://github.com/sharetribe/sharetribe#payments
* https://github.com/sharetribe/sharetribe/issues/2616 (Damn! I haven't yet answered!)
* https://github.com/sharetribe/sharetribe/issues/1462
* https://github.com/sharetribe/sharetribe/issues/1395
* https://github.com/sharetribe/sharetribe/issues/1324
* https://github.com/sharetribe/sharetribe/issues/1155
* https://www.sharetribe.com/community/t/paypal-open-source-integration/288
* https://www.sharetribe.com/community/t/paypal-payment-open-source/131/5

I've heard that some people have made their own PayPal implementation, so if you want to ask from them, I'd kindly direct you to the [Community Forum](https://www.sharetribe.com/community/). We try to keep Github Issues mainly for open issues in the code (bugs).

I'm closing this issue since this is not a bug in the Sharetribe code.

**Closed by rap1ds** 2016-12-08 07:27 UTC
