### ISSUE TITLE
ArgumentError - Missing mandatory value in marketplace_router.rb

### ISSUE THREAD

**Issue by vbklv** [sharetribe/sharetribe#1586] opened 2015-12-05 11:22 UTC
I am getting this error in production environment:

ArgumentError: Error(s) in /data/gocampin/releases/20151203115916/app/utils/marketplace_router.rb:58:in `create_request': host: Missing mandatory value.

It usually happens after several deploys.
But I am still not sure of the pattern.

**Comment by rap1ds** [comment] 2015-12-08 07:41
Hi @vbklv!

Thanks for reporting the issue!

Can you please give us some additional information to make the debugging easier: What's the environment your running your marketplace? Is it Heroku or something else? What's the URL and domain? Are you able to list steps that will reproduce the issue?

**Comment by vbklv** [comment] 2016-01-15 13:28
It is running on an "EngineYard on AWS" T2.Micro instance.
The EngineYard stack is updated to the latest version.
The last merge I made from ST master was with 053f53a.
I cannot reproduce the issue, but I can see it in AirBrake.
It has been occuring in app/utils/entity_utils.rb:370
The strangest thing is that the URL, where the issue occurred, is shown as: http:///
AirBrake also says it occurred on: homepage#index
Here is the backtrace:

app/utils/entity_utils.rb:370 in block in build
app/utils/entity_utils.rb:412 in call
app/utils/entity_utils.rb:412 in with_result
app/utils/entity_utils.rb:362 in build
app/utils/marketplace_router.rb:58 in create_request
app/utils/marketplace_router.rb:73 in needs_redirect
app/controllers/application_controller.rb:280 in perform_redirect
/gems/activesupport-3.2.21/lib/active_support/callbacks.rb:451 in _run__522928984007279325__process_action__2519183754609322796__callbacks
/gems/activesupport-3.2.21/lib/active_support/callbacks.rb:405 in __run_callback
/gems/activesupport-3.2.21/lib/active_support/callbacks.rb:385 in _run_process_action_callbacks
/gems/activesupport-3.2.21/lib/active_support/callbacks.rb:81 in run_callbacks
/gems/actionpack-3.2.21/lib/abstract_controller/callbacks.rb:17 in process_action
/gems/actionpack-3.2.21/lib/action_controller/metal/rescue.rb:29 in process_action
/gems/actionpack-3.2.21/lib/action_controller/metal/instrumentation.rb:30 in block in process_action
/gems/activesupport-3.2.21/lib/active_support/notifications.rb:123 in block in instrument
/gems/activesupport-3.2.21/lib/active_support/notifications/instrumenter.rb:20 in instrument
/gems/activesupport-3.2.21/lib/active_support/notifications.rb:123 in instrument
/gems/actionpack-3.2.21/lib/action_controller/metal/instrumentation.rb:29 in process_action
/gems/actionpack-3.2.21/lib/action_controller/metal/params_wrapper.rb:207 in process_action
/gems/activerecord-3.2.21/lib/active_record/railties/controller_runtime.rb:18 in process_action
/gems/newrelic_rpm-3.9.1.236/lib/new_relic/agent/instrumentation/rails3/action_controller.rb:40 in block in process_action
/gems/newrelic_rpm-3.9.1.236/lib/new_relic/agent/instrumentation/controller_instrumentation.rb:364 in perform_action_with_newrelic_trace
/gems/newrelic_rpm-3.9.1.236/lib/new_relic/agent/instrumentation/rails3/action_controller.rb:39 in process_action
/gems/actionpack-3.2.21/lib/abstract_controller/base.rb:121 in process
/gems/actionpack-3.2.21/lib/abstract_controller/rendering.rb:45 in process
/gems/actionpack-3.2.21/lib/action_controller/metal.rb:203 in dispatch
/gems/actionpack-3.2.21/lib/action_controller/metal/rack_delegation.rb:14 in dispatch
/gems/actionpack-3.2.21/lib/action_controller/metal.rb:246 in block in action
/gems/actionpack-3.2.21/lib/action_dispatch/routing/route_set.rb:73 in call
/gems/actionpack-3.2.21/lib/action_dispatch/routing/route_set.rb:73 in dispatch
/gems/actionpack-3.2.21/lib/action_dispatch/routing/route_set.rb:36 in call
/gems/journey-1.0.4/lib/journey/router.rb:68 in block in call
/gems/journey-1.0.4/lib/journey/router.rb:56 in each
/gems/journey-1.0.4/lib/journey/router.rb:56 in call
/gems/actionpack-3.2.21/lib/action_dispatch/routing/route_set.rb:608 in call
/gems/newrelic_rpm-3.9.1.236/lib/new_relic/agent/instrumentation/middleware_tracing.rb:57 in call
/gems/omniauth-1.2.2/lib/omniauth/strategy.rb:186 in call!
/gems/omniauth-1.2.2/lib/omniauth/strategy.rb:164 in call
/gems/newrelic_rpm-3.9.1.236/lib/new_relic/agent/instrumentation/middleware_tracing.rb:57 in call
/gems/newrelic_rpm-3.9.1.236/lib/new_relic/rack/error_collector.rb:50 in traced_call
/gems/newrelic_rpm-3.9.1.236/lib/new_relic/agent/instrumentation/middleware_tracing.rb:55 in call
/gems/newrelic_rpm-3.9.1.236/lib/new_relic/rack/agent_hooks.rb:26 in traced_call
/gems/newrelic_rpm-3.9.1.236/lib/new_relic/agent/instrumentation/middleware_tracing.rb:55 in call
/gems/newrelic_rpm-3.9.1.236/lib/new_relic/rack/browser_monitoring.rb:23 in traced_call
/gems/newrelic_rpm-3.9.1.236/lib/new_relic/agent/instrumentation/middleware_tracing.rb:55 in call
lib/rack_middleware/custom_domain_cookie.rb:20 in call
/gems/newrelic_rpm-3.9.1.236/lib/new_relic/agent/instrumentation/middleware_tracing.rb:57 in call
/gems/warden-1.2.3/lib/warden/manager.rb:35 in block in call
/gems/warden-1.2.3/lib/warden/manager.rb:34 in catch
/gems/warden-1.2.3/lib/warden/manager.rb:34 in call
/gems/newrelic_rpm-3.9.1.236/lib/new_relic/agent/instrumentation/middleware_tracing.rb:57 in call
/gems/actionpack-3.2.21/lib/action_dispatch/middleware/best_standards_support.rb:17 in call
/gems/newrelic_rpm-3.9.1.236/lib/new_relic/agent/instrumentation/middleware_tracing.rb:57 in call
/gems/rack-1.4.7/lib/rack/etag.rb:23 in call
/gems/newrelic_rpm-3.9.1.236/lib/new_relic/agent/instrumentation/middleware_tracing.rb:57 in call
/gems/rack-1.4.7/lib/rack/conditionalget.rb:25 in call
/gems/newrelic_rpm-3.9.1.236/lib/new_relic/agent/instrumentation/middleware_tracing.rb:57 in call
/gems/actionpack-3.2.21/lib/action_dispatch/middleware/head.rb:14 in call
/gems/newrelic_rpm-3.9.1.236/lib/new_relic/agent/instrumentation/middleware_tracing.rb:57 in call
/gems/actionpack-3.2.21/lib/action_dispatch/middleware/params_parser.rb:21 in call
/gems/newrelic_rpm-3.9.1.236/lib/new_relic/agent/instrumentation/middleware_tracing.rb:57 in call
/gems/actionpack-3.2.21/lib/action_dispatch/middleware/flash.rb:242 in call
/gems/newrelic_rpm-3.9.1.236/lib/new_relic/agent/instrumentation/middleware_tracing.rb:57 in call
/gems/rack-1.4.7/lib/rack/session/abstract/id.rb:210 in context
/gems/rack-1.4.7/lib/rack/session/abstract/id.rb:205 in call
/gems/newrelic_rpm-3.9.1.236/lib/new_relic/agent/instrumentation/middleware_tracing.rb:57 in call
/gems/actionpack-3.2.21/lib/action_dispatch/middleware/cookies.rb:341 in call
/gems/newrelic_rpm-3.9.1.236/lib/new_relic/agent/instrumentation/middleware_tracing.rb:57 in call
/gems/activerecord-3.2.21/lib/active_record/query_cache.rb:64 in call
/gems/newrelic_rpm-3.9.1.236/lib/new_relic/agent/instrumentation/middleware_tracing.rb:57 in call
/gems/activerecord-3.2.21/lib/active_record/connection_adapters/abstract/connection_pool.rb:479 in call
/gems/newrelic_rpm-3.9.1.236/lib/new_relic/agent/instrumentation/middleware_tracing.rb:57 in call
/gems/actionpack-3.2.21/lib/action_dispatch/middleware/callbacks.rb:28 in block in call
/gems/activesupport-3.2.21/lib/active_support/callbacks.rb:405 in _run__1049281033532033158__call__4205775414416463475__callbacks
/gems/activesupport-3.2.21/lib/active_support/callbacks.rb:405 in __run_callback
/gems/activesupport-3.2.21/lib/active_support/callbacks.rb:385 in _run_call_callbacks
/gems/activesupport-3.2.21/lib/active_support/callbacks.rb:81 in run_callbacks
/gems/actionpack-3.2.21/lib/action_dispatch/middleware/callbacks.rb:27 in call
/gems/newrelic_rpm-3.9.1.236/lib/new_relic/agent/instrumentation/middleware_tracing.rb:57 in call
/gems/actionpack-3.2.21/lib/action_dispatch/middleware/remote_ip.rb:31 in call
/gems/newrelic_rpm-3.9.1.236/lib/new_relic/agent/instrumentation/middleware_tracing.rb:57 in call
/gems/newrelic_rpm-3.9.1.236/lib/new_relic/agent/instrumentation/middleware_tracing.rb:57 in call
/gems/actionpack-3.2.21/lib/action_dispatch/middleware/debug_exceptions.rb:16 in call
/gems/newrelic_rpm-3.9.1.236/lib/new_relic/agent/instrumentation/middleware_tracing.rb:57 in call
/gems/actionpack-3.2.21/lib/action_dispatch/middleware/show_exceptions.rb:56 in call
/gems/newrelic_rpm-3.9.1.236/lib/new_relic/agent/instrumentation/middleware_tracing.rb:57 in call
/gems/lograge-0.3.4/lib/lograge/rails_ext/rack/logger.rb:15 in call_app
/gems/railties-3.2.21/lib/rails/rack/logger.rb:16 in block in call
/gems/activesupport-3.2.21/lib/active_support/tagged_logging.rb:22 in tagged
/gems/railties-3.2.21/lib/rails/rack/logger.rb:16 in call
/gems/newrelic_rpm-3.9.1.236/lib/new_relic/agent/instrumentation/middleware_tracing.rb:57 in call
/gems/actionpack-3.2.21/lib/action_dispatch/middleware/request_id.rb:22 in call
/gems/newrelic_rpm-3.9.1.236/lib/new_relic/agent/instrumentation/middleware_tracing.rb:57 in call
/gems/rack-1.4.7/lib/rack/methodoverride.rb:21 in call
/gems/newrelic_rpm-3.9.1.236/lib/new_relic/agent/instrumentation/middleware_tracing.rb:57 in call
/gems/rack-1.4.7/lib/rack/runtime.rb:17 in call
/gems/newrelic_rpm-3.9.1.236/lib/new_relic/agent/instrumentation/middleware_tracing.rb:57 in call
/gems/activesupport-3.2.21/lib/active_support/cache/strategy/local_cache.rb:72 in call
/gems/newrelic_rpm-3.9.1.236/lib/new_relic/agent/instrumentation/middleware_tracing.rb:57 in call
/gems/rack-1.4.7/lib/rack/lock.rb:15 in call
/gems/newrelic_rpm-3.9.1.236/lib/new_relic/agent/instrumentation/middleware_tracing.rb:57 in call
/gems/actionpack-3.2.21/lib/action_dispatch/middleware/static.rb:83 in call
/gems/newrelic_rpm-3.9.1.236/lib/new_relic/agent/instrumentation/middleware_tracing.rb:57 in call
/gems/rack-cache-1.2/lib/rack/cache/context.rb:136 in forward
/gems/rack-cache-1.2/lib/rack/cache/context.rb:245 in fetch
/gems/rack-cache-1.2/lib/rack/cache/context.rb:185 in lookup
/gems/rack-cache-1.2/lib/rack/cache/context.rb:66 in call!
/gems/rack-cache-1.2/lib/rack/cache/context.rb:51 in call
/gems/newrelic_rpm-3.9.1.236/lib/new_relic/agent/instrumentation/middleware_tracing.rb:57 in call
/gems/newrelic_rpm-3.9.1.236/lib/new_relic/agent/instrumentation/middleware_tracing.rb:57 in call
/gems/railties-3.2.21/lib/rails/engine.rb:484 in call
/gems/railties-3.2.21/lib/rails/application.rb:231 in call
/gems/railties-3.2.21/lib/rails/railtie/configurable.rb:30 in method_missing
/gems/newrelic_rpm-3.9.1.236/lib/new_relic/agent/instrumentation/middleware_tracing.rb:57 in call
/gems/rack-1.4.7/lib/rack/deflater.rb:13 in call
/gems/newrelic_rpm-3.9.1.236/lib/new_relic/agent/instrumentation/middleware_tracing.rb:57 in call
/usr/libexec/passenger/rubylib/phusion_passenger/rack/thread_handler_extension.rb:74 in process_request
/usr/libexec/passenger/rubylib/phusion_passenger/request_handler/thread_handler.rb:141 in accept_and_process_next_request
/usr/libexec/passenger/rubylib/phusion_passenger/request_handler/thread_handler.rb:109 in main_loop
/usr/libexec/passenger/rubylib/phusion_passenger/request_handler.rb:455 in block (3 levels) in start_threads

**Comment by rap1ds** [comment] 2016-01-19 08:06
Thanks for additional information!

There indeed seems to be something wrong with the URL. The URL is `http:///` is probably the reason why the `host` is `nil` and why you get the `Missing mandatory value` error.

It's very hard to guess where the issue is but it's probably somehow related to your DNS/Proxy/etc configurations.

To me it looks that this is not an error in Sharetribe codebase. Since there are no clear way to reproduce the issue, I'll close the issue for now. Feel free to post additional information or steps to reproduce to this step if you find something new.

**Closed by rap1ds** 2016-01-19 08:06 UTC
Labels: more information needed
